### ISSUE TITLE
win7 x64 1920*1080  the font is super small

### ISSUE THREAD

**Issue by CrazyBeginner** [vran-dev/PrettyZoo#100]

**Comment by vran-dev** [comment]
- what version you are using ?
 - Have you changed the windows's default font?
 
you can also take a screenshot to help me find the root cause

**Comment by CrazyBeginner** [comment]
v1.4.0 ， not change  the windows's default font

![image](https://user-images.githubusercontent.com/5567096/107107620-2e278d00-686d-11eb-82c9-2b9304e22f91.png)

**Comment by vran-dev** [comment]
Sorry for waiting so long

I released [v1.6.0](https://github.com/vran-dev/PrettyZoo/releases/tag/v1.6.0) just now.

from v1.6.0,  you can change global font size to solve this problem

If you have any issue anyway, you can create new issue
