### ISSUE TITLE
希望能将node中的 ctime 和 mtime 加个可读性强的格式

### ISSUE THREAD

**Issue by cantfu** [vran-dev/PrettyZoo#102]
## PrettyZoo 版本
version: v2.0
type: msi

## 操作系统版本
windows 10

## 本地 JDK 版本
11

## 问题描述
无

## 日志信息
```java
```

**Comment by vran-dev** [comment]
@cantfu 

你可以通过点击 ctim / mtime 标签名称切换日期格式

![](https://github.com/vran-dev/PrettyZoo/raw/master/release/img/time-format.gif)
