### ISSUE TITLE
考虑导入导出功能吗

### ISSUE THREAD

**Issue by Joeyscat** [vran-dev/PrettyZoo#13]
你好，请问考虑做个节点导入与导出功能吗

**Comment by vran-dev** [comment]
> 你好，请问考虑做个节点导入与导出功能吗

这一块的场景目前还没想明白，不知你是什么场景需要呢？
-  如果用于备份的话，基于第三方的 shell 脚本更合适一些

从功能完备性出发，静态结构的导入与导出还涉及很多冲突点
- 导出时，临时节点需要导出吗
- 导入时，某个 server 节点存在，但是 data 不一样
- 导入时，某个 server 节点存在，但是节点类型不同（一个是持久，一个是临时）

**Comment by Joeyscat** [comment]
感谢指导！有个项目需要zookeeper作为配置中心，想用工具导入现成的配置，看到zkui有这样的功能。因为zookeeper还不熟，没有考虑到这些问题，所以..我试试脚本应该可以了，谢谢。
