### ISSUE TITLE
Could support cluster mode?

### ISSUE THREAD

**Issue by ralphhuang** [vran-dev/PrettyZoo#135]
看wiki上写的是单个节点数据可视，支持集群吗？如果支持，如何填写配置？试了逗号分割ip不行

**Comment by vran-dev** [comment]
> 看wiki上写的是单个节点数据可视，支持集群吗？如果支持，如何填写配置？试了逗号分割ip不行

底层是支持的，不过目前没有对用户放开这个限制。

如果你确实需要集群可视化，我会在下个版本放开这个限制，欢迎到时候帮我验证一下

**Comment by vran-dev** [comment]
Sorry，我最近尝试了一下支持集群模式，虽然数据的 CRUD 是正常的，但与其它既有功能却有冲突

- 4 letter command ，不兼容
- 命令行模式，不兼容
- SSH Tunnel，不兼容

鉴于改动成本很高，所以短期内是不会支持集群模式的，不过我会朝着这方面进行努力

（如果你也有这样的需求，可以点个赞，我会将其优先级提高）
