### ISSUE TITLE
数据更新后metadata未刷新

### ISSUE THREAD

**Issue by JiyongShi** [vran-dev/PrettyZoo#138]
## PrettyZoo 版本
version: v1.7.0
type: exe

## 操作系统版本
windows 10

## 本地 JDK 版本
无

## 问题描述
创建测试节点  /test
点击“更新”，更新测试节点数据
mtime、dateversion等元数据未刷新

## 日志信息
```java
```

**Comment by vran-dev** [comment]
稍晚点我会去尝试重现这个问题

Thanks for your response

**Comment by vran-dev** [comment]
我在 PR #139 修复了这个 bug，最终会 release 在 v1.7.1 这个版本里面。

再次感谢你的反馈
