### ISSUE TITLE
dubbo 注册url不显示完整

### ISSUE THREAD

**Issue by mysterin** [vran-dev/PrettyZoo#14]
dubbo 服务注册到 zookeeper 的 url 非常长，但是没有完整显示，超过字数会省略。
所以建议在显示节点信息时加多一个字段展示完整 URL，并且可以选中复制。

**Comment by vran-dev** [comment]
> dubbo 服务注册到 zookeeper 的 url 非常长，但是没有完整显示，超过字数会省略。
> 所以建议在显示节点信息时加多一个字段展示完整 URL，并且可以选中复制。

hello, 你可以尝试以下 V0.3.1 版本

https://github.com/vran-dev/PrettyZoo/releases/tag/v0.3.1
