### ISSUE TITLE
Deepin v20.x installed failed

### ISSUE THREAD

**Issue by pmzgit** [vran-dev/PrettyZoo#140]
## PrettyZoo 版本
version: v1.7.0
type: deb

## 操作系统版本
deepin v20.x 

Linux node.p1 5.7.7-amd64-desktop #75 SMP Mon Aug 24 20:38:46 CST 2020 x86_64 GNU/Linux

## 本地 JDK 版本
1.8.0_261-b12

## 问题描述
```sh
准备解压 prettyzoo_1.7.0-1_amd64.deb  ...
正在解压 prettyzoo (1.7.0-1) ...
正在设置 prettyzoo (1.7.0-1) ...
xdg-desktop-menu: No writable system menu directory found.
dpkg: 处理软件包 prettyzoo (--install)时出错：
 已安装 prettyzoo 软件包 post-installation 脚本 子进程返回错误状态 3
在处理时有错误发生：
 prettyzoo
```
## 日志信息
```java
```

**Comment by vran-dev** [comment]
我在[这里](https://askubuntu.com/questions/405800/installation-problem-xdg-desktop-menu-no-writable-system-menu-directory-found)找到有类似的错误

简单来说就是先创建目录再安装软件，你可以尝试一下

> sudo mkdir /usr/share/desktop-directories/

如果有问题可以持续反馈

**Comment by vran-dev** [comment]
@pmzgit 问题还存在吗？ 如果已经解决的话可以贴一下解决方案，这个 issue 将会被 close 掉
