### ISSUE TITLE
Some thoughts and suggestions

### ISSUE THREAD

**Issue by TinyZzh** [vran-dev/PrettyZoo#151]
## ISSUE

version: latest

platform: 

- [✔ ] windows 10

package type: platform default

OS version: Windows10 

description:

提几个不成熟的想法和建议

Q1：可以新增无JRE的release包，使用系统默认的JRE环境
可以有效的减小安装包的大小。目前github下载网络不稳定，安装包越小越好

Q2：zk操作体验有待改进
不支持批量操作、删除等节点。想操作批量删除节点时，需要一个一个操作
不支持右键弹窗。不是很符合一般软件的操作直觉，

Q3：界面布局不是很合理
左侧的zk列表比较直观，感受比较好，但是config按钮有点突兀。
删除节点按钮比较隐晦，不明显

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
非常感谢你的建议

- Q1 我想根本这个问题的根本原因还是网络问题，后续我会尝试找一个国内的 Release Binary 下载地址。

- Q2 我单独拆分为两个需求
        - 支持节点多选删除操作
        - 支持右键节点弹窗操作

- Q3.1  随着主菜单按钮的增加，这个菜单栏设计也会有相应的调整的。
- Q3.2  删除菜单的按钮可能会放到节点的右键菜单 (Q2) 中去

Best regards
