### ISSUE TITLE
节点不刷新

### ISSUE THREAD

**Issue by RuoBingCoder** [vran-dev/PrettyZoo#154]
## 节点不刷新
 

1. 不知道例如Dubbo 某个服务节点，点击刷新不刷新节点数据

**Comment by vran-dev** [comment]
@RuoBingCoder 

你的版本号是多少呢？

刷新以后 dataVersion 字段会有变化，你可以观察以下

另一种可能就是 dubbo 会自己定时刷新节点的数据
