### ISSUE TITLE
创建、修改节点数据长度问题

### ISSUE THREAD

**Issue by kenixFog** [vran-dev/PrettyZoo#156]
## ISSUE

version: latest

platform: 

- [ √ ] windows
- [ ] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:  通过PrettyZoo执行命令【create /node "123" 】后node节点的数据长度显示为5，set一样，但通过zk提供的zkCli.cmd执行同样命令后，通过PrettyZoo查看节点，数据显示长度为3

what happened ? your expected ?

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
hello，五一假期没能及时回复。

这是因为在创建节点数据 `"123` 时，两个双引号也被当作数据存储了。

ps：目前命令行还无法 100% 还原 zkCli 的功能
