### ISSUE TITLE
win10: couldn't install in default directory

### ISSUE THREAD

**Issue by webeasymail** [vran-dev/PrettyZoo#173]
## ISSUE

version:  v1.9.1

platform: 

 windows

package type: platform default

OS version: Windows10 

description:

![image](https://user-images.githubusercontent.com/4695614/117936531-8b811d80-b337-11eb-8bca-21f5be9fd560.png)

**Comment by vran-dev** [comment]
@webeasymail  切换为其它目录可以安装吗？
