### ISSUE TITLE
macOS 打开app 提示已损坏

### ISSUE THREAD

**Issue by yakirChen** [vran-dev/PrettyZoo#174]
## macOS 打开app 提示已损坏

version: 1.9.1

platform: 

- [ ] windows
- [x] mac
- [ ] Linux

![image](https://user-images.githubusercontent.com/22702893/117959911-0d307580-b34f-11eb-80a5-a020c53cf8e3.png)

**Comment by vran-dev** [comment]
@yakirChen 
可以试一下这个解决方案
 https://www.macwk.com/article/mac-catalina-1015-file-damage

**Comment by yakirChen** [comment]
> @yakirChen 
> 
> 可以试一下这个解决方案
> 
>  https://www.macwk.com/article/mac-catalina-1015-file-damage 

谢谢提供解决方案

我自己编译下试试
