### ISSUE TITLE
Node data show hex mode?

### ISSUE THREAD

**Issue by llxwj** [vran-dev/PrettyZoo#177]
Raw data show support hex mode??

**Comment by vran-dev** [comment]
@llxwj 
could you detail your story? 
such as, raw data example and expect formatted data exmpale

**Comment by llxwj** [comment]
就是类似于winhex,或者是其他的十六进制编辑器的显示模式, zookeeer 节点上的数据不全是字符串格式的,比如把C的结构体存放到zookeeper节点上的形式.
