### ISSUE TITLE
Add confirm when request refresh data 

### ISSUE THREAD

**Issue by yshaojie** [vran-dev/PrettyZoo#181]
PrettyZoo非常好用，很感激作者。
不过有个建议：
能否在更新node值的时候添加一个确认弹窗，直接更新会导致误操作。

想象以下场景
某个node值更新很频繁，当我查看这个值的时候，不小心点击到了更新操作，实际界面上的值已经不是最新的了
这样就会旧值覆盖新值，造成严重的后果。
![image](https://user-images.githubusercontent.com/3929820/119941276-f6328a00-bfc2-11eb-9607-983a27f02cdd.png)

**Comment by yshaojie** [comment]
追加一个
添加一个刷新功能，这样比较方便的看节点新值

**Comment by vran-dev** [comment]
Good idea,  I will add cofirm when node data has been changed.

**Comment by vran-dev** [comment]
done, see #182

**Comment by yshaojie** [comment]
谢谢@vran-dev大神
