### ISSUE TITLE
Support SSH login with  secret

### ISSUE THREAD

**Issue by Panpannn** [vran-dev/PrettyZoo#190]
看配置只有ssh账密登录,请问后续支持ssh密钥登录吗

**Comment by vran-dev** [comment]
Thanks for your advice

我会去调研并尝试实现

**Comment by kanevbg** [comment]
+1 Really that's a must

**Comment by vran-dev** [comment]
long time no see, the feature ssh login by secret will meet in the next version, see pr #293
