### ISSUE TITLE
MACOS install failed

### ISSUE THREAD

**Issue by prFor** [vran-dev/PrettyZoo#195]
## ISSUE![image](https://user-images.githubusercontent.com/4089611/122860075-a344bc00-d34f-11eb-8b77-309f097acf6d.png)
version: latest

platform: 

- [ ] windows
- [V] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

![image](https://user-images.githubusercontent.com/4089611/122860075-a344bc00-d34f-11eb-8b77-309f097acf6d.png)log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
see also #180
