### ISSUE TITLE
prettyZoo is damaged and cannot be opened.

### ISSUE THREAD

**Issue by parzulpan** [vran-dev/PrettyZoo#200]
## ISSUE

version: latest

platform: 

- [ ] windows
- [x] mac
- [ ] Linux

package type: platform default

OS version: macOS Big Sur 11.3.1

description:

Double click the icon to tell me the error. prettyZoo is damaged and cannot be opened.

log:

> you can find log in {user.home}/.prettyZoo/log

![Snipaste_2021-07-08_20-13-31](https://user-images.githubusercontent.com/34685042/124919575-fcd40880-e028-11eb-9a40-21e4c39459e9.png)

**Comment by vran-dev** [comment]
macOS 客户端如果提示 “Catalina xxx.app已损坏，无法打开，你应该将它移到废纸篓解决方法”.
可以参考https://www.macwk.com/article/mac-catalina-1015-file-damage 文章解决。

see at #25

**Comment by parzulpan** [comment]
thanks!
