### ISSUE TITLE
删除功能，是否可以增加二次确认？

### ISSUE THREAD

**Issue by YunaiV** [vran-dev/PrettyZoo#21]
在试用的时候，不小心点到删除按钮，结果直接删除了。

还是蛮危险的~

**Comment by vran-dev** [comment]
good idea

我会尝试在下一个小版本增加这个功能，实现以后会关闭该 issue

**Comment by YunaiV** [comment]
给力。

周末写了一篇简单的文章，推荐支持下！

http://vip.iocoder.cn/Zookeeper/PrettyZoo/

**Comment by vran-dev** [comment]
> 给力。
> 
> 周末写了一篇简单的文章，推荐支持下！
> 
> http://vip.iocoder.cn/Zookeeper/PrettyZoo/

非常感谢你的推荐， 给予了我更大的动力！
