### ISSUE TITLE
Does it support M1 chip？

### ISSUE THREAD

**Issue by hua-hnust** [vran-dev/PrettyZoo#215]
## ISSUE

version: latest

platform: 

- [ ] windows
- [ ] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

what happened ? your expected ?

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
I have no M1 machine and i will try to do cross compile, but i can't guarantee it will be success.

**Comment by MarkKC** [comment]
不支持m1

**Comment by FakeCore** [comment]
It supports the m1 platform now.

**Comment by charlotte-xiao** [comment]
try this on your terminal
```shell
sudo spctl --master-disable 
sudo xattr -r -d com.apple.quarantine /Applications/prettyZoo.app
```

**Comment by Mrmanbanpai** [comment]
After downloading release dmg, it appears to be corrupted during installation
M1 Pro 12.4

**Comment by shawnl111** [comment]
@charlotte-xiao 谢谢！成功了
