### ISSUE TITLE
占内存，连接3个Zookeeper,内存占用超3gb,断开连接后，内存占用也没有恢复

### ISSUE THREAD

**Issue by dufengming2008** [vran-dev/PrettyZoo#216]
如题

**Comment by vran-dev** [comment]
能提供一下详细的环境信息吗？比如系统版本、单个 zookeeper 的节点数量以及使用的 prettyZoo 版本

**Comment by dufengming2008** [comment]
CentOS + zookeeper 3.5.6集群（三个服务器） + numChildren 439

**Comment by dufengming2008** [comment]
> （包括）奥里马德·奥夫特

CentOS + zookeeper 3.5.6集群（三个服务器） + numChildren 439
