### ISSUE TITLE
windows-msi can`t connection zookeeper-server

### ISSUE THREAD

**Issue by secondchilde** [vran-dev/PrettyZoo#217]
## ISSUE

version: latest

platform: 

- [ ] windows

package type: platform default

OS version: Windows10 

description:

can save confgurition , but when i click connect . Waiting for about a minute will prompt failure , And the connection can be established through the zkCli.cmd command

**Comment by vran-dev** [comment]
can you provide a log to me ? it could help me to location the problem quickly

you can find log in `${user.home}/.prettyZoo/log`

**Comment by secondchilde** [comment]
![image](https://user-images.githubusercontent.com/37492906/130186626-65684fd6-8a55-48e5-81ea-cf4d76644418.png)

**Comment by vran-dev** [comment]
It seems that  caused by connect timeout (over than 3 seconds)

**Comment by secondchilde** [comment]
I found the reason, because the steps of zkserver.cmd need to be modified, I didn't modify it. Now it's OK. Modified content:

"-Dzookeeper.audit.enable=true"
Thank you for your answer!
![image](https://user-images.githubusercontent.com/37492906/130189233-522058ab-2c39-479d-b52f-76b1f42cfb1b.png)
