### ISSUE TITLE
macOS build is broken

### ISSUE THREAD

**Issue by artheus** [vran-dev/PrettyZoo#219]
## ISSUE

versions: 
- v1.9.3
- v1.9.2
- v1.9.1

platform: 

- [ ] windows
- [x] mac
- [ ] Linux

package type: platform default

OS version: macOS Big Sur 11.5.2 (20G95)

description:

**what happened?**
I tried to open the application after installing. And I keep getting the following error message:
![image](https://user-images.githubusercontent.com/618946/130778739-9c8a498b-4726-483c-8da6-b3dda9ae80bf.png)

**what's expected?**
I expected the application to open normally

The last version to function properly was `v1.9.0`

log:

No logs created...

**Comment by vran-dev** [comment]
first:
```shell
sudo spctl --master-disable
```

second:
open System Preferences->Security & Privacy 
select **anywhere**

final: reinstall prettyZoo

**Comment by artheus** [comment]
@vran-dev So you are suggesting I disable my security assessment for downloaded software?
No thank you.

**Comment by artheus** [comment]
```
$ spctl --status
assessments disabled
```

![image](https://user-images.githubusercontent.com/618946/130790892-6749eacd-51e7-457a-8f82-6b7db3359c00.png)

This was already configured on my device. So that is not working..

**Comment by artheus** [comment]
Also this:

```
$ spctl --assess -v ~/Downloads/prettyZoo.app
/Users/artheus/Downloads/prettyZoo.app: accepted
override=security disabled
```

`spctl` considers it `accepted`

**Comment by vran-dev** [comment]
try to run it and then open the application

```shell
xattr -rc /Applications/prettyZoo.app
```

**Comment by bobwenx** [comment]
Move the install path from `/Applications` to `~/Applications`, 
then, simply call `xattr` is enough.
```
xattr -rc /Applications/prettyZoo.app
```
No need to change `System Policy` to launch the app.
