### ISSUE TITLE
不支持 mac m1怎么办？

### ISSUE THREAD

**Issue by hk758** [vran-dev/PrettyZoo#221]
## ISSUE

version: latest

platform: 

- [ ] windows
- [ ] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

what happened ? your expected ?

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
很抱歉，由于 prettyZoo 现在打包使用的是 github action 的服务，而官方的服务目前不支持 m1 宿主机。
我本身也没有 m1 的设备，所以暂时是无法进行编译和验证的。

如果你有 m1 的设备并且知道如何构建 Java 项目的话，可以自己尝试一下

参考文档：https://github.com/vran-dev/PrettyZoo/wiki/build-yourself
