### ISSUE TITLE
ssl的连接方式

### ISSUE THREAD

**Issue by caoheyang** [vran-dev/PrettyZoo#225]
## ISSUE

version: latest

platform: 

- [ ] mac

你好，请问ssl的连接方式，有gif图吗？谢谢～～

**Comment by vran-dev** [comment]
如果你想通过 SSL 连接的话 

Zookeeper server & port 其实就是在你本地起一个代理， server 填 localhost 就可以了， port 只要不是被占用的就可以任意填

SSH server 就是你充当代理的服务器，这个需要填写服务地址、用户名称和密码

Remote server 就是 zookeeper 实际部署的服务器，它只能通过 SSH server 来访问
