### ISSUE TITLE
不能打开  显示已损坏 mac  intel

### ISSUE THREAD

**Issue by tixff** [vran-dev/PrettyZoo#226]
## ISSUE

version: latest

platform: 

- [ ] windows
- [ ] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

what happened ? your expected ?

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
请参考 #219 
或者查看 [README](https://github.com/vran-dev/PrettyZoo/blob/master/README_CN.md)
