### ISSUE TITLE
Support sort list

### ISSUE THREAD

**Issue by wuqingfang** [vran-dev/PrettyZoo#230]
## ISSUE
左侧列表是否支持排序 ，或提供自下定义排序功能，多了会乱
version: latest

platform: 

- [ ] windows
- [ ] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

what happened ? your expected ?

log:

> you can find log in {user.home}/.prettyZoo/log

**Comment by vran-dev** [comment]
@wuqingfang  hello, 你指的排序是节点排序 还是 server 列表的排序
