### ISSUE TITLE
java.lang.module.FindException: Hash of javafx.base differs to expected hash   recorded in java.base

### ISSUE THREAD

**Issue by ericheshenghao** [vran-dev/PrettyZoo#231]
## ISSUE

version: latest

platform: 

- [ ] windows
 

package type: platform default

OS version: Windows10 / Ubuntu1804

description:

java.lang.module.FindException: Hash of javafx.base (9649e381ca27950dc6c7499073d7d67da6253188aba80750447c09943acbc03e) differs to expected hash (eed990643d4226c5fcf0e04f285b5a67926ea2e1417251ce48bb883b8591c6b9) recorded in java.base
 
![image](https://user-images.githubusercontent.com/21009212/143666231-80b82f84-6966-4315-8956-0117d8b40ddb.png)

期望：运行成功

**Comment by vran-dev** [comment]
你本地使用的 jdk 版本是多少呢？这种情况先 clean 一下试试

**Comment by ericheshenghao** [comment]
使用jdk17后解决
