### ISSUE TITLE
连接zk集群集群时，只能输入一个ip:port，希望支持connetingString，输入多个

### ISSUE THREAD

**Issue by stefanxfy** [vran-dev/PrettyZoo#232]
连接zk集群集群时，只能输入一个ip:port，希望支持connetingString，输入多个。
然后可以支持动态重连

**Comment by vran-dev** [comment]
@stefanxfy 

动态重连指的是什么？prettyZoo 目前应该是支持断线自动重连的。

输入多个 connect string 是希望连接一个集群吗？
