### ISSUE TITLE
显示文件已损坏

### ISSUE THREAD

**Issue by vichbb** [vran-dev/PrettyZoo#239]
## ISSUE

version: latest

platform: 

- [ ] windows
- [1 ] mac
- [ ] Linux

package type: platform default

OS version: Windows10 / Ubuntu1804

description:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/48641476/149495830-c036af48-da82-463a-a484-7975f2eb083b.png">

what happened ? your expected ?
文件已损坏

log:
> you can find log in {user.home}/.prettyZoo/log
not exists

**Comment by vran-dev** [comment]
https://github.com/vran-dev/PrettyZoo/blob/master/README_CN.md

@vichbb  在 readme 的 [mac 安装问题] 一节中有提到解决方案
