### ISSUE TITLE
Windows  启动出现JVM错误

### ISSUE THREAD

**Issue by doubcrick** [vran-dev/PrettyZoo#24]
![image](https://user-images.githubusercontent.com/6976437/101432554-063aac80-3944-11eb-8cce-c40faeea2715.png)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=17852, tid=18208
#
# JRE version:  (15.0+36) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (15+36-1562, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
#

---------------  S U M M A R Y ------------

Command Line: -Djdk.module.main=app.main app.main/cc.cc1234.PrettyZooApplication

Host: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 8 cores, 15G,  Windows 10 , 64 bit Build 17763 (10.0.17763.475)
Time: Tue Dec  8 10:56:14 2020 ?D1ú±ê×?ê±?? elapsed time: 0.016816 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x000001bcc427f690):  JavaThread "Unknown thread" [_thread_in_vm, id=18208, stack(0x000000557b300000,0x000000557b400000)]

Stack: [0x000000557b300000,0x000000557b400000],  sp=0x000000557b3fec78,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), data execution prevention violation at address 0x0000000000000000

**Comment by zhukaijuke** [comment]
<img width="316" alt="842CE639-27E1-4415-8148-F676511574B5" src="https://user-images.githubusercontent.com/33745482/101435208-e6f14e80-3946-11eb-9ff4-273f6c4c5488.png">
同样打不开, 版本0.3.2, 
另外刚运行exe时提示找不到/prettyZoo/app/prettyZoo-win.cfg, 需要自己重命名文件

**Comment by doubcrick** [comment]
已经重命名了出现的JVM异常
我重新下载最新版本的上一个版本就正常了



369021118@qq.com
 
发件人： 朱凯
发送时间： 2020-12-08 11:22
收件人： vran-dev/PrettyZoo
抄送： doubcrick; Author
主题： Re: [vran-dev/PrettyZoo] 启动出现JVM错误 (#24)
同样打不开, 版本0.3.2, 另外刚运行exe时提示找不到/prettyZoo/app/prettyZoo-win.cfg, 需要自己重命名文件 
―

**Comment by vran-dev** [comment]
感谢各位的使用和反馈，最新版的 windows 打包有问题，我会尽快解决

**Comment by vran-dev** [comment]
@doubcrick  @zhukaijuke 

我刚刚重新构建并上传了windows  v0.3.2 版的,  你们可以尝试一下， 如果有问题可以及时反馈给我

https://github.com/vran-dev/PrettyZoo/releases

**Comment by xzbamiss** [comment]
你们有提示这个吗？   “无法定位到程序输入点 JVM_GetLastErrorString 于动态链接库 D:\...\zip.dll上” 。   目前用的JDK8，环境变量都检查了，系统是win8.1

**Comment by vran-dev** [comment]
> 你们有提示这个吗？ “无法定位到程序输入点 JVM_GetLastErrorString 于动态链接库 D:...\zip.dll上” 。 目前用的JDK8，环境变量都检查了，系统是win8.1

理论上不依赖系统的 Java 环境， 你使用的是哪个版本的 prettyZoo？ 
release 里面的分发包是基于 win10 构建的

**Comment by doubcrick** [comment]
多半是系统问题导致的，我看是把java打包到里面的，跟你本地的java环境无关，只跟你的操作系统有关



369021118@qq.com
 
发件人： vran-dev
发送时间： 2020-12-09 11:18
收件人： vran-dev/PrettyZoo
抄送： doubcrick; Mention
主题： Re: [vran-dev/PrettyZoo] 启动出现JVM错误 (#24)
你们有提示这个吗？ “无法定位到程序输入点 JVM_GetLastErrorString 于动态链接库 D:...\zip.dll上” 。 目前用的JDK8，环境变量都检查了，系统是win8.1
理论上不依赖系统的 Java 环境， 你使用的是哪个版本的 prettyZoo？
release 里面的分发包是基于 win10 构建的

**Comment by xzbamiss** [comment]
> > 你们有提示这个吗？ “无法定位到程序输入点 JVM_GetLastErrorString 于动态链接库 D:...\zip.dll上” 。 目前用的JDK8，环境变量都检查了，系统是win8.1
> 
> 理论上不依赖系统的 Java 环境， 你使用的是哪个版本的 prettyZoo？
> release 里面的分发包是基于 win10 构建的

最新的0.3.2

**Comment by vran-dev** [comment]
> > > 你们有提示这个吗？ “无法定位到程序输入点 JVM_GetLastErrorString 于动态链接库 D:...\zip.dll上” 。 目前用的JDK8，环境变量都检查了，系统是win8.1
> > 
> > 
> > 理论上不依赖系统的 Java 环境， 你使用的是哪个版本的 prettyZoo？
> > release 里面的分发包是基于 win10 构建的
> 
> 最新的0.3.2

是今天刚下载的吗？ 我昨晚上有重新打包过一版 0.3.2， 在 win10 和 win7 验证是可以运行的

**Comment by xzbamiss** [comment]
> > > > 你们有提示这个吗？ “无法定位到程序输入点 JVM_GetLastErrorString 于动态链接库 D:...\zip.dll上” 。 目前用的JDK8，环境变量都检查了，系统是win8.1
> > > 
> > > 
> > > 理论上不依赖系统的 Java 环境， 你使用的是哪个版本的 prettyZoo？
> > > release 里面的分发包是基于 win10 构建的
> > 
> > 
> > 最新的0.3.2
> 
> 是今天刚下载的吗？ 我昨晚上有重新打包过一版 0.3.2， 在 win10 和 win7 验证是可以运行的

是的，早上刚下的。 刚又试了0.3.1，可以用
![1](https://user-images.githubusercontent.com/17397623/101570892-45373380-3a12-11eb-896e-feb7c844ffb8.png)

**Comment by vran-dev** [comment]
## 解决方案

0.3.2 打包时使用了 JDK 15 的镜像， 如果你的机器上有其他低于 11 的 Java 版本，在启动的时候就会崩溃。

我目前已经将打包依赖的 JDK 降级到了 14， v0.3.2 重新上传了 windows 版本安装包。

同时在 v1.0.0 中我还加入 Linux 发行版可用的 deb、rpm 安装包

https://github.com/vran-dev/PrettyZoo/releases/tag/v1.0.0
