### ISSUE TITLE
每次轻点一下节点 整个列表就在那颤抖1秒

### ISSUE THREAD

**Issue by zj2626** [vran-dev/PrettyZoo#240]
当鼠标放在某个节点上 然后再轻点一下节点 整个列表就在那颤抖1秒

**Comment by biggerboy** [comment]
> 当鼠标放在某个节点上 然后再轻点一下节点 整个列表就在那颤抖1秒

哪个版本，什么操作系统？

**Comment by WowYouCanReallyDance** [comment]
两位大佬好牛批哦。 太屌屌了。界面整的好漂亮。 感觉JavaFX太难上手了
