### ISSUE TITLE
界面显示乱码

### ISSUE THREAD

**Issue by MaxSherry** [vran-dev/PrettyZoo#243]
![image](https://user-images.githubusercontent.com/3919535/155050399-97535073-f6a7-47f7-9d77-388da60098ad.png)

用最新的版本,还是旧的版本的prettyZoo, 在windows10 21H2 下边一直显示乱码,能否看一下是哪里导致的

**Comment by vran-dev** [comment]
![image](https://user-images.githubusercontent.com/12870335/155050710-5c2dd828-e6af-4226-89ff-3c82c686f167.png)

将语言切换为英文是否存在同样的问题？

**Comment by MaxSherry** [comment]
![image](https://user-images.githubusercontent.com/3919535/155070524-7a7008c0-e930-4598-93eb-4a1fd55e05ae.png)

切换成英文也是同样的问题

**Comment by MaxSherry** [comment]
问题找到了, 是我windows平台自己安装了新的雅黑字体, 不知道为什么这个雅黑字体不兼容 perettyZoo , 我把自己安装的雅黑字体卸载后, 显示正常了. 谢谢
