### ISSUE TITLE
mac客户端炸了

### ISSUE THREAD

**Issue by littleEric** [vran-dev/PrettyZoo#244]
![image](https://user-images.githubusercontent.com/19311150/155682370-f5b4ff75-9b01-4b05-ae9d-01219b327bc0.png)
系统版本：macOS Monterey
机型：MacBook Pro 2020 (Intel)

**Comment by vran-dev** [comment]
https://github.com/vran-dev/PrettyZoo/blob/master/README_CN.md

@littleEric  在 readme 的 [mac 安装问题] 一节中有提到解决方案

**Comment by littleEric** [comment]
ok，谢谢

vran ***@***.***> 于2022年2月25日周五 16:39写道：
