### ISSUE TITLE
mac os big sur安装问题

### ISSUE THREAD

**Issue by YuXuguang** [vran-dev/PrettyZoo#25]
mac os big sur 安装提示“prettyZoo.app已损坏，无法打开。您应该将它移到废纸篓”，尝试v0.3.2和v0.3.1版本均不行
<img width="258" alt="WX20201208-105815@2x" src="https://user-images.githubusercontent.com/10458102/101434977-83ffb780-3946-11eb-87d3-f73421834ef3.png">

**Comment by vran-dev** [comment]
友情提示：macOS 客户端如果提示 “Catalina xxx.app已损坏，无法打开，你应该将它移到废纸篓解决方法”，可以参考https://www.macwk.com/article/mac-catalina-1015-file-damage 文章解决。

非常感谢你的反馈

**Comment by YuXuguang** [comment]
按你说的已经解决，感谢
