### ISSUE TITLE
how to connect using connection string ?

### ISSUE THREAD

**Issue by sramaram-rythmos** [vran-dev/PrettyZoo#252]
Hi @vran-dev 
thank you for this great app!

I am trying to connect to a zookeeper cluster using a connection string (similar to ZooInspector) - Is it supported ? If yes, how ? Pleas guide.

**Comment by vran-dev** [comment]
@sramaram-rythmos 

not support yet, because it's conflict with terminal mode now.

I will figure out a way to support it in a future version

**Comment by sramaram-rythmos** [comment]
@vran-dev  thanks for the quick reponse.

is there a workaround ?

**Comment by vran-dev** [comment]
@sramaram-rythmos 

now the only way is connect single one server, not the cluster
