### ISSUE TITLE
大佬，你的项目怎么跑起来啊，我是纯小白

### ISSUE THREAD

**Issue by shijianzugouniai** [vran-dev/PrettyZoo#262]

**Comment by shijianzugouniai** [comment]
![image](https://user-images.githubusercontent.com/86582822/169267394-739b9b60-dedb-45bf-a46b-ce62e28f7627.png)

**Comment by shijianzugouniai** [comment]
![Uploading image.png…]()

**Comment by shijianzugouniai** [comment]
![image](https://user-images.githubusercontent.com/86582822/169267750-22228910-6e33-4655-a603-d0a60b41cfa9.png)

**Comment by vran-dev** [comment]
@shijianzugouniai  参考这里

https://github.com/vran-dev/PrettyZoo/wiki/build-yourself

用 `./gradlew app:run` 运行

**Comment by shijianzugouniai** [comment]
![image](https://user-images.githubusercontent.com/86582822/169274462-de0011a6-5f84-4882-bb16-6ddcf4a10307.png)
大佬，是我太菜了，回寝室的时候再看看

**Comment by shijianzugouniai** [comment]
![ATG5~QFS`ZLQI%1}2%`6K~V](https://user-images.githubusercontent.com/86582822/169282770-d1453c63-99e7-4073-ab3f-2e5a3a56fcf8.png)

**Comment by vran-dev** [comment]
你的  jdk 版本太低了，需要 14+

**Comment by shijianzugouniai** [comment]
![image](https://user-images.githubusercontent.com/86582822/169424336-1a18e5ef-2c4a-43e6-9a9d-34a0691270f7.png)
感谢大佬深夜解答我这个纯小白，早上上课用学校机房的电脑运行好了(学校机房电脑还是顶[哭笑])，下午再用自己电脑再实验一下

**Comment by shijianzugouniai** [comment]
大佬没有开赞赏平台吗？不可以打赏吗？感谢大佬

**Comment by vran-dev** [comment]
感谢，我在另一个项目 https://doc.databasir.com/#/donate/index 开通了赞赏。

这个问题解决了吗？如果没问题的话记得关一下 close issue 哈

**Comment by shijianzugouniai** [comment]
![屏幕截图 2022-05-21 110839](https://user-images.githubusercontent.com/86582822/169634131-3e1cd3df-d176-47a3-b09f-4fac533586f5.png)
大佬，我在我的电脑上运行好了，感谢大佬，请问我如果想要做一下这个项目，是将代码从头到尾自己敲一遍吗？

**Comment by shijianzugouniai** [comment]
大佬，您发的赞赏链接打不开啊
![image](https://user-images.githubusercontent.com/86582822/169634766-386875f3-80d9-4a78-aa91-ff810fccfc41.png)

**Comment by vran-dev** [comment]
> ![屏幕截图 2022-05-21 110839](https://user-images.githubusercontent.com/86582822/169634131-3e1cd3df-d176-47a3-b09f-4fac533586f5.png) 大佬，我在我的电脑上运行好了，感谢大佬，请问我如果想要做一下这个项目，是将代码从头到尾自己敲一遍吗？

这之前你是否有以下背景

- 了解 javaFX  基础的概念和 API
- 了解 zookeeper 基础的概念和操作
- 了解 Apache curator 框架的基础 API

有了这些以后再参考本项目代码，基本就能自己实现了

**Comment by vran-dev** [comment]
> 大佬，您发的赞赏链接打不开啊 ![image](https://user-images.githubusercontent.com/86582822/169634766-386875f3-80d9-4a78-aa91-ff810fccfc41.png)

https://github.com/vran-dev/PrettyZoo ， 本项目 README 页面已放赞赏码

**Comment by shijianzugouniai** [comment]
不好意思，大佬，可能是我电脑的问题，GitHub总是打不开，看到消息也不能及时回复您

**Comment by shijianzugouniai** [comment]
![image](https://user-images.githubusercontent.com/86582822/169655476-8794fa55-bc38-45f2-bb54-c5f17654e237.png)

**Comment by shijianzugouniai** [comment]
学校交了一点ZooKeeper，还有SSM相关的一些框架，其他的真的没有怎么听说过，这样也可以吗？边敲边学

**Comment by shijianzugouniai** [comment]
希望大佬您不要嫌弃我的赞赏

**Comment by shijianzugouniai** [comment]
大佬，您之前的项目的图好像都不能看了，总是显示不出来，Wiki那边也是

**Comment by vran-dev** [comment]
非常感谢你的赞助

**Comment by vran-dev** [comment]
图片问题应该是国内网络的导致的

你可以先看看  JavaFX 的基础 API，参考：https://www.yiibai.com/javafx/javafx-tutorial-for-beginners.html

**Comment by shijianzugouniai** [comment]
感谢大佬指导我这个小白(膜拜)，希望早日能将您的项目自己能实现一遍(编码能力太菜了，哭笑)，看完了就可以直接动手做了吗？

**Comment by vran-dev** [comment]
你可以先自己做一个简单的项目开始

**Comment by shijianzugouniai** [comment]
看过一个博主用Java写的一个JavaFX日记项目，感觉很好奇https://github.com/wxxlamp/WxxDiary，在学校的时候想多学一点东西，想把大佬您的项目能弄明白

**Comment by shijianzugouniai** [comment]
![image](https://user-images.githubusercontent.com/86582822/169744426-61824e02-e357-4a27-a590-8461c7fb5b93.png)
主要是想瞻仰，看看大佬您是怎么写代码的[羡慕]

**Comment by vran-dev** [comment]
加油，这个 issue 我就关了，后续有其他问题可以在  discussion 里讨论

**Comment by shijianzugouniai** [comment]
感谢大佬，长期支持您
