### ISSUE TITLE
是否可以配置 jute.maxbuffer 呢？

### ISSUE THREAD

**Issue by moyu0** [vran-dev/PrettyZoo#265]
## 参数可以在哪里配置呢

更改了zookeeper启动时的jute.maxbuffer参数以增加节点存储大小，之后PrettyZoo就无法使用了，会一直重连。
我在(Windows10) prettyZoo\app\prettyZoo.cfg 里添加了 jute.maxbuffer=10240000，也没有解决问题。
我尝试添加了jute.maxbuffer 环境变量也不管用。
请问是不支持配置此参数吗？还是我没有找对配置的地方

**Comment by vran-dev** [comment]
最好能提供一下 prettyZoo 系统日志，便于定位异常

**Comment by vran-dev** [comment]
@moyu0  

刚刚已发布新版本，可以在 `${user.home}/.prettyZoo/` 目录下创建 `zookeeper.properties` 去指定配置

https://github.com/vran-dev/PrettyZoo/releases/tag/v1.9.7

**Comment by moyu0** [comment]
感谢作者👍
