### ISSUE TITLE
你好，Zookeeper开启了SASL/Digest-MD5认证，该怎么设置连接？

### ISSUE THREAD

**Issue by hellsam** [vran-dev/PrettyZoo#269]
## Description

> detail your question, such as build question or usage question

**Comment by DuyjCat** [comment]
同问啊，按照又上角的ACL格式写好配置，不管用啊

**Comment by itstrongs** [comment]
同问，配了SASL连不上了

**Comment by WhiteStart** [comment]
同问，zookeeper启用了auth之后如何连接

**Comment by WhiteStart** [comment]
下载源码，在app/build.gradle中加入SASL配置可以连接成功
def runArgsValue = [
        "-XX:+UnlockExperimentalVMOptions",
        // required due to a bug in Java: https://github.com/javafxports/openjdk-jfx/issues/175
        "-Djava.security.auth.login.config={your_path}/jaas.conf",
