### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by wq1019** [vran-dev/PrettyZoo#27]
There is no response, no error report, and no background process.

os: windows 10
version: [v0.3.1](https://github.com/vran-dev/PrettyZoo/tree/v0.3.1)

**Comment by vran-dev** [comment]
can you find the log file in `{user.home}/.prettyZoo/pretty.log` ?

**Comment by vran-dev** [comment]
> There is no response, no error report, and no background process.
> 
> os: windows 10
> version: [v0.3.1](https://github.com/vran-dev/PrettyZoo/tree/v0.3.1)

hello, you can try the latest version (v0.3.2), i just rebuild it and uploaded

https://github.com/vran-dev/PrettyZoo/releases

**Comment by vran-dev** [comment]
same question #24 , you can find solution at  #24

**Comment by vran-dev** [comment]
gg
