### ISSUE TITLE
软件版本展示及检测更新

### ISSUE THREAD

**Issue by biggerboy** [vran-dev/PrettyZoo#270]
## What

目前使用Windows版本，安装后，没有地方查看目前安装的是哪个版本，无法与GitHub上已发布的版本对比确认是不是最新版。下载的文件名也没有版本标识，加上版本号也能方便查看之前下载的版本号。
另外，希望可以加自动版本检测，提示有新版本，或者可以在线更新。

## Why

方便确认自己安装的版本。
方便版本升级。
感谢。

**Comment by vran-dev** [comment]
closed by PR #278
