### ISSUE TITLE
“prettyZoo”已损坏，无法打开。 您应该将它移到废纸篓。bug report

### ISSUE THREAD

**Issue by Sleeeeeeeping** [vran-dev/PrettyZoo#272]
## Environment

* version: `{ prettyZoo version, such as 1.9.6 }`
* distribution: `{ prettyZoo distribution, such as win \ mac \ linux }`
* OS version: `{such as Windows10 / Ubuntu1804}`

## Description

> details what happened and expected

## Logs

> you can find log in {user.home}/.prettyZoo/log

<img width="283" alt="image" src="https://user-images.githubusercontent.com/108887396/188258384-c2171e5d-c5a7-4467-b23b-0014377a9a03.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/108887396/188258390-50a81b20-67f6-4461-aa7b-f9c53be901cd.png">

**Comment by vran-dev** [comment]
@Sleeeeeeeping 

有试过 readme 里面的解决方案吗？ https://github.com/vran-dev/PrettyZoo/blob/master/README_CN.md
