### ISSUE TITLE
连接zk集群频繁出现重连

### ISSUE THREAD

**Issue by dujie-js** [vran-dev/PrettyZoo#273]
![zk断连](https://user-images.githubusercontent.com/56857589/189099896-44064113-d9fe-463d-87a6-8c0291a67cb4.png)
zk内容较多不知道是否是内容量影响连接的稳定性

**Comment by js20166098** [comment]
疑似客户端和对应的zk不匹配

**Comment by vran-dev** [comment]
i test version  from 3.4 to 3.8, and not meet your situation, but now support configure zookeeper connection timeout

see pr #279 , it will release at next version

**Comment by dujie-js** [comment]
![image](https://user-images.githubusercontent.com/56857589/204071917-cfffaae0-22e6-485f-9806-9fa4e6f5e718.png)
我记得有某几个版本的zk使用的这个依赖2.0版本的,具体公司的zk版本确实不清楚

**Comment by dujie-js** [comment]
![image](https://user-images.githubusercontent.com/56857589/204071974-72e005b1-8616-451e-bf9e-6926ae65a321.png)
这是软件的异常信息

**Comment by dujie-js** [comment]
@vran-dev

**Comment by dujie-js** [comment]
[prettyZoo.log](https://github.com/vran-dev/PrettyZoo/files/10095697/prettyZoo.log)
软件完整的日志文件 版本是最新的2.0

**Comment by dujie-js** [comment]
还有配置超时时间保存时
![image](https://user-images.githubusercontent.com/56857589/204073355-ece8acd9-8a8b-4409-a833-02b6c5f6c429.png)

**Comment by vran-dev** [comment]
> ![image](https://user-images.githubusercontent.com/56857589/204071917-cfffaae0-22e6-485f-9806-9fa4e6f5e718.png) 我记得有某几个版本的zk使用的这个依赖2.0版本的,具体公司的zk版本确实不清楚

目前推测有两种情况
1.  集群选举导致的连接丢失
2.  会话心跳检测失败导致的连接丢失

如果是 2 的话其实重试是可以解决的

**Comment by dujie-js** [comment]
> 

看起来不像是2 ,确实在不断的重试,但是一直都提示连接丢失,网络问题也应该可以不考虑,生产环境的稳定性应该不会这个差,但是集群选举导致丢失也不应该呀,而且我尝试进行修改超时时间保存的时候也有问题,就是最后的那个图

**Comment by vran-dev** [comment]
如果是版本兼容性问题的话，初始连接就会有问题，目前从截图来看已经有数据同步了，估计还是和集群有关，后续我尝试支持一下集群多实例连接。
超时时间保存失败的问题能否帮忙复现并提供一下日志

**Comment by dujie-js** [comment]
超时那个我尝试在日志看但是没有日志,而且页面闪的太快了,可以的话要不你可以远程看一下

**Comment by dujie-js** [comment]
或者我这有个录屏文件
链接: https://pan.baidu.com/s/1zYNke0itEPGgRXG_f_I1dA?pwd=6tyz 提取码: 6tyz 复制这段内容后打开百度网盘手机App，操作更方便哦
你可以看一下视频这样可以吗

**Comment by vran-dev** [comment]
可以的，非常感谢，后续我会修复问题
