### ISSUE TITLE
please support ubuntu install pkg

### ISSUE THREAD

**Issue by fywxin** [vran-dev/PrettyZoo#28]

**Comment by vran-dev** [comment]
I will try to do it, thx

**Comment by vran-dev** [comment]
I build rpm and deb package, I launched success on Ubuntu , you can download it at 

https://github.com/vran-dev/PrettyZoo/releases/tag/v1.0.0

if you have any problem, you can report it here

**Comment by fywxin** [comment]
Well done！thank～
