### ISSUE TITLE
每次打开软件更新都提示失败

### ISSUE THREAD

**Issue by dujie-js** [vran-dev/PrettyZoo#295]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/56857589/205435199-a58bb23f-444e-482a-90f3-67229eb3b7eb.png">

**Comment by dujie-js** [comment]
最新版本2.0

**Comment by dujie-js** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/56857589/205435378-0cb45b16-05eb-4b33-8898-7539f6265247.png">

**Comment by vran-dev** [comment]
版本校验是基于 github 的 api 来实现的，github 对同一个 ip 的匿名调用会有限流，如果一段时间内调用次数超过阈值就会被限制从而导致 check update failed
