### ISSUE TITLE
win11安装2.1版本

### ISSUE THREAD

**Issue by MorganArthur** [vran-dev/PrettyZoo#303]
## Description
![image](https://user-images.githubusercontent.com/24489342/209595500-f15d2ce1-e19d-4c85-826f-7592373c3394.png)

**Comment by vran-dev** [comment]
2.0.0 版本有同样的问题吗？

**Comment by lizhuquan0769** [comment]
我也是，安装完2.1.0打开提示“Faod to launch JVM”，本机装的是oracle jvm 1.8

**Comment by lizhuquan0769** [comment]
> 我也是，安装完2.1.0打开提示“Faod to launch JVM”，本机装的是oracle jvm 1.8

然后我安装上一个版本2.0.0，没问题

**Comment by vran-dev** [comment]
> > 我也是，安装完2.1.0打开提示“Faod to launch JVM”，本机装的是oracle jvm 1.8
> 
> 然后我安装上一个版本2.0.0，没问题

安装的是 msi 还是 zip 版本？

**Comment by vran-dev** [comment]
请升级到 `v2.1.1.PRE` 版本

https://github.com/vran-dev/PrettyZoo/releases/tag/v2.1.1.PRE
