### ISSUE TITLE
mac版在后台会一直尝试连接zk服务器并占用大量资源吗？

### ISSUE THREAD

**Issue by YuFanUsername** [vran-dev/PrettyZoo#304]
## Description

> detail your question, such as build question or usage question
mac在后台运行程序，zk处于连接状态，把zk服务的资源打满了，导致oom

**Comment by vran-dev** [comment]
正常只有在连接失败的时候会重试，有通过 oom 的日志能确定是 prettZoo 的连接导致的吗？
