### ISSUE TITLE
bug report : windows server 2012R2 could not run

### ISSUE THREAD

**Issue by getchu** [vran-dev/PrettyZoo#307]
## Environment

* version: `prettyZoo v2.1.0 msi`
* distribution: `prettyZoo distribution,  win`
* OS version: ` windows server 2012R2`

## Description

> msi install success ,  but run failed

**Comment by vran-dev** [comment]
请升级到 `v2.1.1.PRE` 版本

https://github.com/vran-dev/PrettyZoo/releases/tag/v2.1.1.PRE
