### ISSUE TITLE
clickhouse用的zk，节点几百万，一直在重连

### ISSUE THREAD

**Issue by WillMeng** [vran-dev/PrettyZoo#308]
zk版本：3.5.5
由于clickhouse表和字段非常多，zk的节点达到了几百万，一直在重连，最后电脑cpu飙升到80%，强杀进程了，希望优化一下，谢谢

**Comment by echollee** [comment]
连接zk 3.5.9，watches飙升几十万，最后zk节点OOM，关闭prettyZoo就恢复正常了。
连接zk 3.7版本，没发现这个问题。
