### ISSUE TITLE
win11  安装后，双击没有任何反应

### ISSUE THREAD

**Issue by niejian** [vran-dev/PrettyZoo#309]
## Description

> detail your question, such as build question or usage question
安装 最新版 msi(2.1.0)，双击打开没有任何反应

**Comment by vran-dev** [comment]
请升级到 `v2.1.1.PRE` 版本

https://github.com/vran-dev/PrettyZoo/releases/tag/v2.1.1.PRE

**Comment by niejian** [comment]
> 请升级到 `v2.1.1.PRE` 版本
> 
> https://github.com/vran-dev/PrettyZoo/releases/tag/v2.1.1.PRE

* 没有此目录：`{系统用户目录}\.prettyZoo\log`
* 系统中有jdk17，默认1.8
* 升级到2.1.1pre，打开报错

![image](https://user-images.githubusercontent.com/7080323/218625551-58a4ca8f-16ca-471e-9498-ff1808a59d5f.png)

**Comment by vran-dev** [comment]
@niejian  1.8 用的哪个发行版，oracle 还是 openJDK？ 

尝试将 JAVA_HOME 切换到 17 试试

目前怀疑是和本地 JDK 有冲突， 但我尝试在本地装了 Oracle Java8、Open JDK 8  均没有复现

**Comment by niejian** [comment]
> 


oracle java8的版本，环境变量设置的就是1.8

**Comment by vran-dev** [comment]
执行一下 `java -version` 看看版本号，我去找对应版本看看能否复现

**Comment by niejian** [comment]
![image](https://user-images.githubusercontent.com/7080323/218646104-eca8d97c-5066-41f4-8065-59fc2b4b3212.png)

**Comment by vran-dev** [comment]
目前网上基本找不到 161 版本了我没法复现，你试试以下几个方案看能否启动成功

- 将 `JAVA_HOME` 环境变量置空再启动试试看能否启动？
- 将 `JAVA_HOME` 环境变量指向更高版本的 JDK 试试看能否启动？
