### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by cnzexin** [vran-dev/PrettyZoo#310]
![image](https://user-images.githubusercontent.com/31715758/217799105-829b5514-abbe-4f34-9f8f-d0bacdd2a01f.png)

## Environment

* version: `v2.1.0`
* distribution: `mac`
* OS version: `Ventura 13.1 (22C65)`

## Description

> “prettyZoo”已损坏，无法打开。 你应该将它移到废纸篓。

## Logs

> No log

**Comment by vran-dev** [comment]
参考 https://github.com/vran-dev/PrettyZoo/issues/219 的解决方案
