### ISSUE TITLE
jdk1.8使用哪个版本的

### ISSUE THREAD

**Issue by supermanShuSheng** [vran-dev/PrettyZoo#312]
jdk1.8使用哪个版本的

**Comment by supermanShuSheng** [comment]
我是jdk1.8  安装的最新的2.1.1pre 然后报错 failed to launch jvm 是什么原因

**Comment by vran-dev** [comment]
由于我目前还没有复现，你试试以下几个方案

- 将 JAVA_HOME 环境变量置空再启动试试看能否启动？
- 将 JAVA_HOME 环境变量指向更高版本的 JDK 试试看能否启动？

你也可以帮忙使用  `java -version` 命令看看你本机的 JDK 版本号是多少，便于我尝试复现

**Comment by rendongyang111** [comment]
我使用了JDK17也提示 failed to launch jvm

**Comment by rendongyang111** [comment]
![image](https://user-images.githubusercontent.com/38315794/221806681-adc118bb-9890-4e61-bf95-ab32ac2baf20.png)
![image](https://user-images.githubusercontent.com/38315794/221806745-1670330f-3b50-45aa-a53c-4f12135fb12a.png)
![image](https://user-images.githubusercontent.com/38315794/221806777-047d7b4b-68ca-4e4e-9860-48f03ae7ecb4.png)

**Comment by vran-dev** [comment]
> 我使用了JDK17也提示 failed to launch jvm

试试最新版 https://github.com/vran-dev/PrettyZoo/releases/tag/v2.1.1
