### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by klllmxx** [vran-dev/PrettyZoo#313]
Environment: Windows7 Basic Home

version: prettyZoo version  2.0

Description
When open desktop icon,can not to work ,Install and uninstall is repeatedly more time but nothing happen！
please fix this one ！

Picture show down blow:
![图片](https://user-images.githubusercontent.com/87749576/218613532-5ed42493-f8f0-4020-a221-be66327031ee.png)

**Comment by vran-dev** [comment]
Do you hava installed a JDK? 

if hava, what's version of your jdk(use `java -version` to show it)?

try using the following solutions

- set  `JAVA_HOME`  environment variables to null and then run prettyZoo

**Comment by klllmxx** [comment]
> 

ok I will do you say,thank you bro!

**Comment by klllmxx** [comment]
And one suggestion to install action is better i think？When doing setup action if not find jdk env can consider reminding user to install given java  software version,exit the installation process,else successfully to finsh setup!You can think about this one,to you  bro!!

**Comment by klllmxx** [comment]
okok! I checking my Win7 OS just now ,can not find any about  JDK installed but installed IDEA before,

**Comment by Will-well** [comment]
![image](https://user-images.githubusercontent.com/22841502/221395887-16e667e2-b700-4ab5-9105-f4419174f261.png)

**Comment by vran-dev** [comment]
application failed to launch fixed in version  [v2.1.1](https://github.com/vran-dev/PrettyZoo/releases/tag/v2.1.1 ), try it
