### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DingChuanV** [vran-dev/PrettyZoo#314]
## mac Ventura使用不了

> 显示PrettyZoo已损坏，无法打开，你应该将它移到废纸篓

**Comment by vran-dev** [comment]
打开终端执行命令即可

> xattr -rc /Applications/prettyZoo.app

详情参考 https://github.com/vran-dev/PrettyZoo/issues/219

**Comment by DingChuanV** [comment]
sudo xattr -rd com.apple.quarantine /Applications/prettyZoo.app
可以解决

**Comment by vran-dev** [comment]
问题已解决， issue 关闭
