### ISSUE TITLE
可视化界面显示信息显示不全

### ISSUE THREAD

**Issue by lians0** [vran-dev/PrettyZoo#318]
可视化界面上未显示提供者
![image](https://user-images.githubusercontent.com/30581350/221735594-ca88c175-da4c-43fe-8a5e-337c5078d019.png)

使用命令查看时存在提供者的
![image](https://user-images.githubusercontent.com/30581350/221735493-e36c0a12-46b6-4df8-9fed-09a55125d0e6.png)

使用版本：V2.1.1

**Comment by vran-dev** [comment]
使用的 zookeeper 版本是多少？

**Comment by lians0** [comment]
> 使用的 zookeeper 版本是多少？

 3.4.12

**Comment by lians0** [comment]
研究了一番是节点权限的问题，之前那个节点需要digest权限。
请问我有zk超级管理员的用户名和密码怎么配置
