### ISSUE TITLE
MacOS Ventura M1 启动后立即退出

### ISSUE THREAD

**Issue by JasonMing** [vran-dev/PrettyZoo#319]
应用移动到 `~/Applications/` 下，通过 `xattr -rc ~/Applications/prettyZoo.app` 方式让 app 启动。
但启动后没有显示任何窗口，过几秒后应用自动退出。

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/1220848/221741645-03cbb7ee-09d8-4880-8663-52e529d5b98d.png">

**Comment by vran-dev** [comment]
目前使用的是什么版本？

1. 进入终端
2. 定位 prettyZoo app 的目录， 比如 `~/Application/prettyZoo.app/Contents/runtime/Contents/Home/bin`
3. 执行 `./prettyZoo`
4. 查看终端日志

**Comment by JasonMing** [comment]
@vran-dev 问题已经确定，对旧版配置兼容有问题爆 NPE 了
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/1220848/223313341-d6fc769d-80b9-407d-b8a9-89bbfc61f264.png">
