### ISSUE TITLE
PrettyZoo客户端无法安装

### ISSUE THREAD

**Issue by ketianlin** [vran-dev/PrettyZoo#324]
我的电脑是deepin 系统的，下载的deb包，无法安装
提示:
dpkg: trying script from the new package instead ...
dpkg: ... it looks like that went OK
xdg-desktop-menu: No writable system menu directory found.
dpkg: error processing package prettyzoo (--install):
 installed prettyzoo package post-installation script subprocess returned error exit status 3
Errors were encountered while processing:
 prettyzoo

是什么原因

**Comment by vran-dev** [comment]
试试先创建目录再安装

 `sudo mkdir /usr/share/desktop-directories/`

**Comment by ketianlin** [comment]
>谢谢大佬,可以了,就是创建一下那个目录后就可以了
