### ISSUE TITLE
打不开Failed to launch JVM

### ISSUE THREAD

**Issue by leizi86** [vran-dev/PrettyZoo#326]
之前一直正常使用，有天重启后就打不开了，无论哪个版本都一样，我把系统里java相关的变量全都干掉了也不行
![image](https://user-images.githubusercontent.com/33827471/225578867-813946b5-9a50-4729-9cf4-3f8ef61e5be9.png)
![image](https://user-images.githubusercontent.com/33827471/225578903-9cbb5e7b-6250-4d3a-a256-fd58bff58a8b.png)
![image](https://user-images.githubusercontent.com/33827471/225579467-b3386221-fdb5-4a6c-a01c-3f82e6867e61.png)

**Comment by vran-dev** [comment]
删除 `~/.prettyzoo/prettZoo.cfg`  配置文件（该操作会清理掉已有的连接配置，如有必要，请先备份），然后再启动试试。

目测可能是配置文件版本冲突导致的

**Comment by leizi86** [comment]
删除后就可以了，感谢大佬
