### ISSUE TITLE
mac安装1.0.0版本，显示已损坏，无法打开

### ISSUE THREAD

**Issue by Epsirong** [vran-dev/PrettyZoo#33]
mac安装1.0.0版本，显示"已损坏，无法打开"，OS： Catalina(10.15.7)

**Comment by vran-dev** [comment]
友情提示：macOS 客户端如果提示 “Catalina xxx.app已损坏，无法打开，你应该将它移到废纸篓解决方法”，可以参考https://www.macwk.com/article/mac-catalina-1015-file-damage 文章解决。

可以按该文的方法解决
