### ISSUE TITLE
Failed to lauch JVM

### ISSUE THREAD

**Issue by tuoeg** [vran-dev/PrettyZoo#333]
i can't run gui,when i try delete config,then restart prettyZoo,also running error
![image](https://user-images.githubusercontent.com/49616374/232375742-45cf94c7-9a4e-4b9c-b782-f09cf97e8bbb.png)

**Comment by vran-dev** [comment]
What is the version you are using?

**Comment by gy1234** [comment]
i also have the same problem, but i tried to block the file(C:\Users\xxx\.accessibility.properties), it worked mormally.
![image](https://github.com/vran-dev/PrettyZoo/assets/25741726/4d711347-8920-49a1-9d3a-c6b3f7f2a49d)

**Comment by kinghuisFFFF** [comment]
me too，我按上述修改配置后，仍无法启动

**Comment by kinghuisFFFF** [comment]
![image](https://github.com/vran-dev/PrettyZoo/assets/100672141/6a9504fe-304c-47ba-afaf-d4300285f469)
