### ISSUE TITLE
希望加上"刷新节点"功能

### ISSUE THREAD

**Issue by wjw465150** [vran-dev/PrettyZoo#335]
希望加上"刷新节点"功能!ZooInspector的刷新功能就非常实用.
![1](https://github.com/vran-dev/PrettyZoo/assets/927155/4e81ed97-8e48-43ba-b772-97feb0c53409)

**Comment by vran-dev** [comment]
prettyZoo 是自动刷新节点的，不需要手动刷新，目前是因为遇到什么问题才需要这个功能码？

**Comment by wjw465150** [comment]
不希望自动刷新,如果节点更新很频繁,会引起很大的性能问题.
