### ISSUE TITLE
0.3.2版本 win10系统打不开

### ISSUE THREAD

**Issue by yuyongkratos** [vran-dev/PrettyZoo#35]
log如下：
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=23240, tid=21376
#
# JRE version:  (15.0+36) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (15+36-1562, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
#

---------------  S U M M A R Y ------------

Command Line: -Djdk.module.main=app.main app.main/cc.cc1234.PrettyZooApplication

Host: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz, 8 cores, 11G,  Windows 10 , 64 bit Build 18362 (10.0.18362.1110)
Time: Wed Dec  9 17:27:50 2020 ?D1ú±ê×?ê±?? elapsed time: 0.028703 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x000002825e793b80):  JavaThread "Unknown thread" [_thread_in_vm, id=21376, stack(0x000000c78a100000,0x000000c78a200000)]

Stack: [0x000000c78a100000,0x000000c78a200000],  sp=0x000000c78a1fef88,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), data execution prevention violation at address 0x0000000000000000

Registers:
RAX=0x000002825ebcaf64, RBX=0x000002827a5a8090, RCX=0x000002825ebcaf64, RDX=0x000000000000034b
RSP=0x000000c78a1fef88, RBP=0x000000c78a1ff0a0, RSI=0x000002825ebcaf47, RDI=0x000002825ebcaf47
R8 =0x000002827a5a8090, R9 =0x00000000000005ce, R10=0x000000c78a1ff000, R11=0x000000000000001c
R12=0x00000000000005ce, R13=0x000002825e793b80, R14=0x000002825e796f90, R15=0x000002825e796f90
RIP=0x0000000000000000, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x000000c78a1fef88)
0x000000c78a1fef88:   00007ffb1873182f 000002827a5a8090
0x000000c78a1fef98:   00007ffb18731873 00000000000005ce
0x000000c78a1fefa8:   0000000000000000 000000c78a1fefe8
0x000000c78a1fefb8:   0000000000000000 000002825ebcaf47
0x000000c78a1fefc8:   00007ffb18731495 000002827a5a8090
0x000000c78a1fefd8:   000000c78a1ff0a0 000002825ebcaf47
0x000000c78a1fefe8:   0000000000000000 000000c78a1ff0a0
0x000000c78a1feff8:   00007ffacc526eaa 000000c7cafefafa
0x000000c78a1ff008:   000000000000034b 00000000000005ce
0x000000c78a1ff018:   ffffffff00000007 0000000086183d01
0x000000c78a1ff028:   0000b68a4511c776 00000000000005ce
0x000000c78a1ff038:   000002825e796f90 000002825e794050
0x000000c78a1ff048:   000002825c3dc580 00000000001dedb1
0x000000c78a1ff058:   0000000000000368 000002825ebcaf47
0x000000c78a1ff068:   00007ffb18731ed3 0000028279d8d500
0x000000c78a1ff078:   0000000000000016 0000000000000000 

Instructions: (pc=0x0000000000000000)
0xffffffffffffff00:   

---------------  P R O C E S S  ---------------

Threads class SMR info:
_java_thread_list=0x00007ffacc8f2fa0, length=0, elements={
}

Java Threads: ( => current thread )

Other Threads:
  0x000002825e7d9de0 GCTaskThread "GC Thread#0" [stack: 0x000000c78a200000,0x000000c78a300000] [id=10448]
  0x000002825e7e7330 ConcurrentGCThread "G1 Main Marker" [stack: 0x000000c78a300000,0x000000c78a400000] [id=25240]
  0x000002825e7e7e30 ConcurrentGCThread "G1 Conc#0" [stack: 0x000000c78a400000,0x000000c78a500000] [id=23296]
  0x000002825e81e710 ConcurrentGCThread "G1 Refine#0" [stack: 0x000000c78a500000,0x000000c78a600000] [id=16908]
  0x0000028279c1f620 ConcurrentGCThread "G1 Young RemSet Sampling" [stack: 0x000000c78a600000,0x000000c78a700000] [id=16440]

=>0x000002825e793b80 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=21376, stack(0x000000c78a100000,0x000000c78a200000)]

Threads with active compile tasks:

VM state: not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None

Heap address: 0x0000000742a00000, size: 3030 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
CDS disabled.
Compressed class space mapped at: 0x0000000800000000-0x0000000840000000, size: 1073741824
Narrow klass base: 0x0000000800000000, Narrow klass shift: 0, Narrow klass range: 0x40000000

GC Precious Log:
 CPUs: 8 total, 8 available
 Memory: 12119M
 Large Page Support: Disabled
 NUMA Support: Disabled
 Compressed Oops: Enabled (Zero based)
 Heap Region Size: 2M
 Heap Min Capacity: 8M
 Heap Initial Capacity: 190M
 Heap Max Capacity: 3030M
 Pre-touch: Disabled
 Parallel Workers: 8
 Concurrent Workers: 2
 Concurrent Refinement Workers: 8
 Periodic GC: Disabled

Heap:
 garbage-first heap   total 194560K, used 0K [0x0000000742a00000, 0x0000000800000000)
  region size 2048K, 1 young (2048K), 0 survivors (0K)
 Metaspace       used 4K, capacity 4480K, committed 4480K, reserved 1056768K
  class space    used 3K, capacity 384K, committed 384K, reserved 1048576K

Heap Regions: E=young(eden), S=young(survivor), O=old, HS=humongous(starts), HC=humongous(continues), CS=collection set, F=free, OA=open archive, CA=closed archive, TAMS=top-at-mark-start (previous, next)
|   0|0x0000000742a00000, 0x0000000742a00000, 0x0000000742c00000|  0%| F|  |TAMS 0x0000000742a00000, 0x0000000742a00000| Untracked 
|   1|0x0000000742c00000, 0x0000000742c00000, 0x0000000742e00000|  0%| F|  |TAMS 0x0000000742c00000, 0x0000000742c00000| Untracked 
|   2|0x0000000742e00000, 0x0000000742e00000, 0x0000000743000000|  0%| F|  |TAMS 0x0000000742e00000, 0x0000000742e00000| Untracked 
|   3|0x0000000743000000, 0x0000000743000000, 0x0000000743200000|  0%| F|  |TAMS 0x0000000743000000, 0x0000000743000000| Untracked 
|   4|0x0000000743200000, 0x0000000743200000, 0x0000000743400000|  0%| F|  |TAMS 0x0000000743200000, 0x0000000743200000| Untracked 
|   5|0x0000000743400000, 0x0000000743400000, 0x0000000743600000|  0%| F|  |TAMS 0x0000000743400000, 0x0000000743400000| Untracked 
|   6|0x0000000743600000, 0x0000000743600000, 0x0000000743800000|  0%| F|  |TAMS 0x0000000743600000, 0x0000000743600000| Untracked 
|   7|0x0000000743800000, 0x0000000743800000, 0x0000000743a00000|  0%| F|  |TAMS 0x0000000743800000, 0x0000000743800000| Untracked 
|   8|0x0000000743a00000, 0x0000000743a00000, 0x0000000743c00000|  0%| F|  |TAMS 0x0000000743a00000, 0x0000000743a00000| Untracked 
|   9|0x0000000743c00000, 0x0000000743c00000, 0x0000000743e00000|  0%| F|  |TAMS 0x0000000743c00000, 0x0000000743c00000| Untracked 
|  10|0x0000000743e00000, 0x0000000743e00000, 0x0000000744000000|  0%| F|  |TAMS 0x0000000743e00000, 0x0000000743e00000| Untracked 
|  11|0x0000000744000000, 0x0000000744000000, 0x0000000744200000|  0%| F|  |TAMS 0x0000000744000000, 0x0000000744000000| Untracked 
|  12|0x0000000744200000, 0x0000000744200000, 0x0000000744400000|  0%| F|  |TAMS 0x0000000744200000, 0x0000000744200000| Untracked 
|  13|0x0000000744400000, 0x0000000744400000, 0x0000000744600000|  0%| F|  |TAMS 0x0000000744400000, 0x0000000744400000| Untracked 
|  14|0x0000000744600000, 0x0000000744600000, 0x0000000744800000|  0%| F|  |TAMS 0x0000000744600000, 0x0000000744600000| Untracked 
|  15|0x0000000744800000, 0x0000000744800000, 0x0000000744a00000|  0%| F|  |TAMS 0x0000000744800000, 0x0000000744800000| Untracked 
|  16|0x0000000744a00000, 0x0000000744a00000, 0x0000000744c00000|  0%| F|  |TAMS 0x0000000744a00000, 0x0000000744a00000| Untracked 
|  17|0x0000000744c00000, 0x0000000744c00000, 0x0000000744e00000|  0%| F|  |TAMS 0x0000000744c00000, 0x0000000744c00000| Untracked 
|  18|0x0000000744e00000, 0x0000000744e00000, 0x0000000745000000|  0%| F|  |TAMS 0x0000000744e00000, 0x0000000744e00000| Untracked 
|  19|0x0000000745000000, 0x0000000745000000, 0x0000000745200000|  0%| F|  |TAMS 0x0000000745000000, 0x0000000745000000| Untracked 
|  20|0x0000000745200000, 0x0000000745200000, 0x0000000745400000|  0%| F|  |TAMS 0x0000000745200000, 0x0000000745200000| Untracked 
|  21|0x0000000745400000, 0x0000000745400000, 0x0000000745600000|  0%| F|  |TAMS 0x0000000745400000, 0x0000000745400000| Untracked 
|  22|0x0000000745600000, 0x0000000745600000, 0x0000000745800000|  0%| F|  |TAMS 0x0000000745600000, 0x0000000745600000| Untracked 
|  23|0x0000000745800000, 0x0000000745800000, 0x0000000745a00000|  0%| F|  |TAMS 0x0000000745800000, 0x0000000745800000| Untracked 
|  24|0x0000000745a00000, 0x0000000745a00000, 0x0000000745c00000|  0%| F|  |TAMS 0x0000000745a00000, 0x0000000745a00000| Untracked 
|  25|0x0000000745c00000, 0x0000000745c00000, 0x0000000745e00000|  0%| F|  |TAMS 0x0000000745c00000, 0x0000000745c00000| Untracked 
|  26|0x0000000745e00000, 0x0000000745e00000, 0x0000000746000000|  0%| F|  |TAMS 0x0000000745e00000, 0x0000000745e00000| Untracked 
|  27|0x0000000746000000, 0x0000000746000000, 0x0000000746200000|  0%| F|  |TAMS 0x0000000746000000, 0x0000000746000000| Untracked 
|  28|0x0000000746200000, 0x0000000746200000, 0x0000000746400000|  0%| F|  |TAMS 0x0000000746200000, 0x0000000746200000| Untracked 
|  29|0x0000000746400000, 0x0000000746400000, 0x0000000746600000|  0%| F|  |TAMS 0x0000000746400000, 0x0000000746400000| Untracked 
|  30|0x0000000746600000, 0x0000000746600000, 0x0000000746800000|  0%| F|  |TAMS 0x0000000746600000, 0x0000000746600000| Untracked 
|  31|0x0000000746800000, 0x0000000746800000, 0x0000000746a00000|  0%| F|  |TAMS 0x0000000746800000, 0x0000000746800000| Untracked 
|  32|0x0000000746a00000, 0x0000000746a00000, 0x0000000746c00000|  0%| F|  |TAMS 0x0000000746a00000, 0x0000000746a00000| Untracked 
|  33|0x0000000746c00000, 0x0000000746c00000, 0x0000000746e00000|  0%| F|  |TAMS 0x0000000746c00000, 0x0000000746c00000| Untracked 
|  34|0x0000000746e00000, 0x0000000746e00000, 0x0000000747000000|  0%| F|  |TAMS 0x0000000746e00000, 0x0000000746e00000| Untracked 
|  35|0x0000000747000000, 0x0000000747000000, 0x0000000747200000|  0%| F|  |TAMS 0x0000000747000000, 0x0000000747000000| Untracked 
|  36|0x0000000747200000, 0x0000000747200000, 0x0000000747400000|  0%| F|  |TAMS 0x0000000747200000, 0x0000000747200000| Untracked 
|  37|0x0000000747400000, 0x0000000747400000, 0x0000000747600000|  0%| F|  |TAMS 0x0000000747400000, 0x0000000747400000| Untracked 
|  38|0x0000000747600000, 0x0000000747600000, 0x0000000747800000|  0%| F|  |TAMS 0x0000000747600000, 0x0000000747600000| Untracked 
|  39|0x0000000747800000, 0x0000000747800000, 0x0000000747a00000|  0%| F|  |TAMS 0x0000000747800000, 0x0000000747800000| Untracked 
|  40|0x0000000747a00000, 0x0000000747a00000, 0x0000000747c00000|  0%| F|  |TAMS 0x0000000747a00000, 0x0000000747a00000| Untracked 
|  41|0x0000000747c00000, 0x0000000747c00000, 0x0000000747e00000|  0%| F|  |TAMS 0x0000000747c00000, 0x0000000747c00000| Untracked 
|  42|0x0000000747e00000, 0x0000000747e00000, 0x0000000748000000|  0%| F|  |TAMS 0x0000000747e00000, 0x0000000747e00000| Untracked 
|  43|0x0000000748000000, 0x0000000748000000, 0x0000000748200000|  0%| F|  |TAMS 0x0000000748000000, 0x0000000748000000| Untracked 
|  44|0x0000000748200000, 0x0000000748200000, 0x0000000748400000|  0%| F|  |TAMS 0x0000000748200000, 0x0000000748200000| Untracked 
|  45|0x0000000748400000, 0x0000000748400000, 0x0000000748600000|  0%| F|  |TAMS 0x0000000748400000, 0x0000000748400000| Untracked 
|  46|0x0000000748600000, 0x0000000748600000, 0x0000000748800000|  0%| F|  |TAMS 0x0000000748600000, 0x0000000748600000| Untracked 
|  47|0x0000000748800000, 0x0000000748800000, 0x0000000748a00000|  0%| F|  |TAMS 0x0000000748800000, 0x0000000748800000| Untracked 
|  48|0x0000000748a00000, 0x0000000748a00000, 0x0000000748c00000|  0%| F|  |TAMS 0x0000000748a00000, 0x0000000748a00000| Untracked 
|  49|0x0000000748c00000, 0x0000000748c00000, 0x0000000748e00000|  0%| F|  |TAMS 0x0000000748c00000, 0x0000000748c00000| Untracked 
|  50|0x0000000748e00000, 0x0000000748e00000, 0x0000000749000000|  0%| F|  |TAMS 0x0000000748e00000, 0x0000000748e00000| Untracked 
|  51|0x0000000749000000, 0x0000000749000000, 0x0000000749200000|  0%| F|  |TAMS 0x0000000749000000, 0x0000000749000000| Untracked 
|  52|0x0000000749200000, 0x0000000749200000, 0x0000000749400000|  0%| F|  |TAMS 0x0000000749200000, 0x0000000749200000| Untracked 
|  53|0x0000000749400000, 0x0000000749400000, 0x0000000749600000|  0%| F|  |TAMS 0x0000000749400000, 0x0000000749400000| Untracked 
|  54|0x0000000749600000, 0x0000000749600000, 0x0000000749800000|  0%| F|  |TAMS 0x0000000749600000, 0x0000000749600000| Untracked 
|  55|0x0000000749800000, 0x0000000749800000, 0x0000000749a00000|  0%| F|  |TAMS 0x0000000749800000, 0x0000000749800000| Untracked 
|  56|0x0000000749a00000, 0x0000000749a00000, 0x0000000749c00000|  0%| F|  |TAMS 0x0000000749a00000, 0x0000000749a00000| Untracked 
|  57|0x0000000749c00000, 0x0000000749c00000, 0x0000000749e00000|  0%| F|  |TAMS 0x0000000749c00000, 0x0000000749c00000| Untracked 
|  58|0x0000000749e00000, 0x0000000749e00000, 0x000000074a000000|  0%| F|  |TAMS 0x0000000749e00000, 0x0000000749e00000| Untracked 
|  59|0x000000074a000000, 0x000000074a000000, 0x000000074a200000|  0%| F|  |TAMS 0x000000074a000000, 0x000000074a000000| Untracked 
|  60|0x000000074a200000, 0x000000074a200000, 0x000000074a400000|  0%| F|  |TAMS 0x000000074a200000, 0x000000074a200000| Untracked 
|  61|0x000000074a400000, 0x000000074a400000, 0x000000074a600000|  0%| F|  |TAMS 0x000000074a400000, 0x000000074a400000| Untracked 
|  62|0x000000074a600000, 0x000000074a600000, 0x000000074a800000|  0%| F|  |TAMS 0x000000074a600000, 0x000000074a600000| Untracked 
|  63|0x000000074a800000, 0x000000074a800000, 0x000000074aa00000|  0%| F|  |TAMS 0x000000074a800000, 0x000000074a800000| Untracked 
|  64|0x000000074aa00000, 0x000000074aa00000, 0x000000074ac00000|  0%| F|  |TAMS 0x000000074aa00000, 0x000000074aa00000| Untracked 
|  65|0x000000074ac00000, 0x000000074ac00000, 0x000000074ae00000|  0%| F|  |TAMS 0x000000074ac00000, 0x000000074ac00000| Untracked 
|  66|0x000000074ae00000, 0x000000074ae00000, 0x000000074b000000|  0%| F|  |TAMS 0x000000074ae00000, 0x000000074ae00000| Untracked 
|  67|0x000000074b000000, 0x000000074b000000, 0x000000074b200000|  0%| F|  |TAMS 0x000000074b000000, 0x000000074b000000| Untracked 
|  68|0x000000074b200000, 0x000000074b200000, 0x000000074b400000|  0%| F|  |TAMS 0x000000074b200000, 0x000000074b200000| Untracked 
|  69|0x000000074b400000, 0x000000074b400000, 0x000000074b600000|  0%| F|  |TAMS 0x000000074b400000, 0x000000074b400000| Untracked 
|  70|0x000000074b600000, 0x000000074b600000, 0x000000074b800000|  0%| F|  |TAMS 0x000000074b600000, 0x000000074b600000| Untracked 
|  71|0x000000074b800000, 0x000000074b800000, 0x000000074ba00000|  0%| F|  |TAMS 0x000000074b800000, 0x000000074b800000| Untracked 
|  72|0x000000074ba00000, 0x000000074ba00000, 0x000000074bc00000|  0%| F|  |TAMS 0x000000074ba00000, 0x000000074ba00000| Untracked 
|  73|0x000000074bc00000, 0x000000074bc00000, 0x000000074be00000|  0%| F|  |TAMS 0x000000074bc00000, 0x000000074bc00000| Untracked 
|  74|0x000000074be00000, 0x000000074be00000, 0x000000074c000000|  0%| F|  |TAMS 0x000000074be00000, 0x000000074be00000| Untracked 
|  75|0x000000074c000000, 0x000000074c000000, 0x000000074c200000|  0%| F|  |TAMS 0x000000074c000000, 0x000000074c000000| Untracked 
|  76|0x000000074c200000, 0x000000074c200000, 0x000000074c400000|  0%| F|  |TAMS 0x000000074c200000, 0x000000074c200000| Untracked 
|  77|0x000000074c400000, 0x000000074c400000, 0x000000074c600000|  0%| F|  |TAMS 0x000000074c400000, 0x000000074c400000| Untracked 
|  78|0x000000074c600000, 0x000000074c600000, 0x000000074c800000|  0%| F|  |TAMS 0x000000074c600000, 0x000000074c600000| Untracked 
|  79|0x000000074c800000, 0x000000074c800000, 0x000000074ca00000|  0%| F|  |TAMS 0x000000074c800000, 0x000000074c800000| Untracked 
|  80|0x000000074ca00000, 0x000000074ca00000, 0x000000074cc00000|  0%| F|  |TAMS 0x000000074ca00000, 0x000000074ca00000| Untracked 
|  81|0x000000074cc00000, 0x000000074cc00000, 0x000000074ce00000|  0%| F|  |TAMS 0x000000074cc00000, 0x000000074cc00000| Untracked 
|  82|0x000000074ce00000, 0x000000074ce00000, 0x000000074d000000|  0%| F|  |TAMS 0x000000074ce00000, 0x000000074ce00000| Untracked 
|  83|0x000000074d000000, 0x000000074d000000, 0x000000074d200000|  0%| F|  |TAMS 0x000000074d000000, 0x000000074d000000| Untracked 
|  84|0x000000074d200000, 0x000000074d200000, 0x000000074d400000|  0%| F|  |TAMS 0x000000074d200000, 0x000000074d200000| Untracked 
|  85|0x000000074d400000, 0x000000074d400000, 0x000000074d600000|  0%| F|  |TAMS 0x000000074d400000, 0x000000074d400000| Untracked 
|  86|0x000000074d600000, 0x000000074d600000, 0x000000074d800000|  0%| F|  |TAMS 0x000000074d600000, 0x000000074d600000| Untracked 
|  87|0x000000074d800000, 0x000000074d800000, 0x000000074da00000|  0%| F|  |TAMS 0x000000074d800000, 0x000000074d800000| Untracked 
|  88|0x000000074da00000, 0x000000074da00000, 0x000000074dc00000|  0%| F|  |TAMS 0x000000074da00000, 0x000000074da00000| Untracked 
|  89|0x000000074dc00000, 0x000000074dc00000, 0x000000074de00000|  0%| F|  |TAMS 0x000000074dc00000, 0x000000074dc00000| Untracked 
|  90|0x000000074de00000, 0x000000074de00000, 0x000000074e000000|  0%| F|  |TAMS 0x000000074de00000, 0x000000074de00000| Untracked 
|  91|0x000000074e000000, 0x000000074e000000, 0x000000074e200000|  0%| F|  |TAMS 0x000000074e000000, 0x000000074e000000| Untracked 
|  92|0x000000074e200000, 0x000000074e200000, 0x000000074e400000|  0%| F|  |TAMS 0x000000074e200000, 0x000000074e200000| Untracked 
|  93|0x000000074e400000, 0x000000074e400000, 0x000000074e600000|  0%| F|  |TAMS 0x000000074e400000, 0x000000074e400000| Untracked 
|  94|0x000000074e600000, 0x000000074e670a48, 0x000000074e800000| 22%| E|  |TAMS 0x000000074e600000, 0x000000074e600000| Complete 

Card table byte_map: [0x0000028270880000,0x0000028270e70000] _byte_map_base: 0x000002826ce6b000

Marking Bits (Prev, Next): (CMBitMap*) 0x000002825e7da4e0, (CMBitMap*) 0x000002825e7da520
 Prev Bits: [0x0000028271460000, 0x00000282743b8000)
 Next Bits: [0x00000282743c0000, 0x0000028277318000)

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Classes unloaded (0 events):
No events

Classes redefined (0 events):
No events

Internal exceptions (0 events):
No events

Events (2 events):
Event: 0.009 Loaded shared library D:\softWare\PrettyZoo\runtime\bin\java.dll
Event: 0.014 loading class java/lang/Object

Dynamic libraries:
0x00007ff747120000 - 0x00007ff74718d000 	D:\softWare\PrettyZoo\prettyZoo.exe
0x00007ffb333e0000 - 0x00007ffb335d0000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffb32d30000 - 0x00007ffb32de2000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffb30e90000 - 0x00007ffb31135000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffb32b90000 - 0x00007ffb32d24000 	C:\WINDOWS\System32\USER32.dll
0x00007ffb30400000 - 0x00007ffb30421000 	C:\WINDOWS\System32\win32u.dll
0x00007ffb32670000 - 0x00007ffb32696000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffb30560000 - 0x00007ffb306f6000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffb30360000 - 0x00007ffb303fe000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffb311a0000 - 0x00007ffb3129a000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffb31e20000 - 0x00007ffb32507000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffb304e0000 - 0x00007ffb3052a000 	C:\WINDOWS\System32\cfgmgr32.dll
0x00007ffb32f20000 - 0x00007ffb32fc9000 	C:\WINDOWS\System32\shcore.dll
0x00007ffb330f0000 - 0x00007ffb3318e000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffb32fd0000 - 0x00007ffb330f0000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffb31670000 - 0x00007ffb319a5000 	C:\WINDOWS\System32\combase.dll
0x00007ffb312a0000 - 0x00007ffb31320000 	C:\WINDOWS\System32\bcryptPrimitives.dll
0x00007ffb30700000 - 0x00007ffb30e81000 	C:\WINDOWS\System32\windows.storage.dll
0x00007ffb32a80000 - 0x00007ffb32b17000 	C:\WINDOWS\System32\sechost.dll
0x00007ffb32810000 - 0x00007ffb328b3000 	C:\WINDOWS\System32\advapi32.dll
0x00007ffb30330000 - 0x00007ffb30353000 	C:\WINDOWS\System32\profapi.dll
0x00007ffb302c0000 - 0x00007ffb3030a000 	C:\WINDOWS\System32\powrprof.dll
0x00007ffb30290000 - 0x00007ffb302a0000 	C:\WINDOWS\System32\UMPDC.dll
0x00007ffb33190000 - 0x00007ffb331e2000 	C:\WINDOWS\System32\shlwapi.dll
0x00007ffb302a0000 - 0x00007ffb302b1000 	C:\WINDOWS\System32\kernel.appcore.dll
0x00007ffb31470000 - 0x00007ffb31487000 	C:\WINDOWS\System32\cryptsp.dll
0x00007ffb326a0000 - 0x00007ffb326ce000 	C:\WINDOWS\System32\IMM32.DLL
0x00007ffb118e0000 - 0x00007ffb118f8000 	D:\softWare\PrettyZoo\runtime\bin\jli.dll
0x00007ffb02d70000 - 0x00007ffb02e19000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1198_none_73b37520d815d61e\COMCTL32.dll
0x00007ffb2d880000 - 0x00007ffb2d897000 	C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
0x00007ffb272c0000 - 0x00007ffb272ca000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffb0f2e0000 - 0x00007ffb0f2f9000 	D:\softWare\PrettyZoo\runtime\bin\vcruntime140.dll
0x00007ffb18d00000 - 0x00007ffb18d0c000 	D:\softWare\PrettyZoo\runtime\bin\vcruntime140_1.dll
0x00007ffaff060000 - 0x00007ffaff0f1000 	D:\softWare\PrettyZoo\runtime\bin\msvcp140.dll
0x00007ffacbe30000 - 0x00007ffacc98c000 	D:\softWare\PrettyZoo\runtime\bin\server\jvm.dll
0x00007ffb32e80000 - 0x00007ffb32e88000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffb1e220000 - 0x00007ffb1e229000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffb29cc0000 - 0x00007ffb29ce4000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffb32df0000 - 0x00007ffb32e5f000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffb29c90000 - 0x00007ffb29cbd000 	C:\WINDOWS\SYSTEM32\winmmbase.dll
0x00007ffb18730000 - 0x00007ffb1873a000 	D:\softWare\PrettyZoo\runtime\bin\jimage.dll
0x00007ffb2fce0000 - 0x00007ffb2fed4000 	C:\WINDOWS\SYSTEM32\DBGHELP.DLL
0x00007ffb2fb00000 - 0x00007ffb2fb2a000 	C:\WINDOWS\SYSTEM32\dbgcore.DLL
0x00007ffb04600000 - 0x00007ffb04625000 	D:\softWare\PrettyZoo\runtime\bin\java.dll

dbghelp: loaded successfully - version: 4.0.5 - missing functions: none
symbol engine: initialized successfully - sym options: 0x614 - pdb path: .;D:\softWare\PrettyZoo;C:\WINDOWS\SYSTEM32;D:\softWare\PrettyZoo\runtime\bin;C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1198_none_73b37520d815d61e;D:\softWare\PrettyZoo\runtime\bin\server

VM Arguments:
jvm_args: -Djdk.module.main=app.main 
java_command: app.main/cc.cc1234.PrettyZooApplication
java_class_path (initial): .
Launcher Type: SUN_STANDARD

[Global flags]
     intx CICompilerCount                          = 4                                         {product} {ergonomic}
     uint ConcGCThreads                            = 2                                         {product} {ergonomic}
     uint G1ConcRefinementThreads                  = 8                                         {product} {ergonomic}
   size_t G1HeapRegionSize                         = 2097152                                   {product} {ergonomic}
    uintx GCDrainStackTargetSize                   = 64                                        {product} {ergonomic}
   size_t InitialHeapSize                          = 199229440                                 {product} {ergonomic}
   size_t MarkStackSize                            = 4194304                                   {product} {ergonomic}
   size_t MaxHeapSize                              = 3177185280                                {product} {ergonomic}
   size_t MaxNewSize                               = 1906311168                                {product} {ergonomic}
   size_t MinHeapDeltaBytes                        = 2097152                                   {product} {ergonomic}
   size_t MinHeapSize                              = 8388608                                   {product} {ergonomic}
    uintx NonNMethodCodeHeapSize                   = 5839372                                {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122909434                              {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122909434                              {pd product} {ergonomic}
    uintx ReservedCodeCacheSize                    = 251658240                              {pd product} {ergonomic}
     bool SegmentedCodeCache                       = true                                      {product} {ergonomic}
   size_t SoftMaxHeapSize                          = 3177185280                             {manageable} {ergonomic}
     bool UseCompressedClassPointers               = true                                 {lp64_product} {ergonomic}
     bool UseCompressedOops                        = true                                 {lp64_product} {ergonomic}
     bool UseG1GC                                  = true                                      {product} {ergonomic}
     bool UseLargePagesIndividualAllocation        = false                                  {pd product} {ergonomic}

Logging:
Log output configuration:
 #0: stdout all=warning uptime,level,tags
 #1: stderr all=off uptime,level,tags

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131
CLASSPATH=.
PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\softWare\apache-maven-3.3.9\bin;D:\softWare\TortoiseSVN\bin;d:\softWare\SQLServer\Microsoft SQL Server\100\Tools\Binn\;d:\softWare\SQLServer\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;D:\softWare\erl10.2\bin;D:\softWare\rabbitmq_server-3.7.9\sbin;D:\softWare\Git\cmd;D:\softWare\nodejs\;D:\softWare\nodejs\node_global;D:\softWare\scala\bin;D:\softWare\sbt\bin;D:\softWare\Go\bin;D:\softWare\Python\Python37\Scripts\;D:\softWare\Python\Python37\;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\yuyong\AppData\Local\atom\bin;D:\softWare\gradle-5.5-rc-1\bin;C:\Users\yuyong\AppData\Local\Microsoft\WindowsApps;D:\softWare\MongoDB\Server\3.2\bin;C:\Users\yuyong\AppData\Roaming\npm;C:\Users\yuyong\AppData\Local\BypassRuntm;D:\softWare\Microsoft VS Code Insiders\bin;C:\Users\yuyong\go\bin;D:\softWare\PyCharm 2019.2.3\bin;;D:\softWare\GoLand 2019.2.3\bin;
USERNAME=yuyong
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

---------------  S Y S T E M  ---------------

OS:
 Windows 10 , 64 bit Build 18362 (10.0.18362.1110)
OS uptime: 2 days 1:08 hours

CPU: total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 142 stepping 10, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, vzeroupper, avx, avx2, aes, clmul, erms, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx, fma, clflush, clflushopt

Memory: 4k page, system-wide physical 12119M (3841M free)
TotalPageFile size 28503M (AvailPageFile size 14148M)
current process WorkingSet (physical memory assigned to process): 14M, peak: 14M
current process commit charge ("private bytes"): 264M, peak: 264M

vm_info: Java HotSpot(TM) 64-Bit Server VM (15+36-1562) for windows-amd64 JRE (15+36-1562), built on Aug 11 2020 22:38:02 by "mach5one" with unknown MS VC++:1925

END.

**Comment by vran-dev** [comment]
是使用的 msi 安装包还是 exe 的安装包？msi 的应该没问题

**Comment by vran-dev** [comment]
Same question  #24
