### ISSUE TITLE
macbook air M1 提示：“prettyZoo”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by jslssz** [vran-dev/PrettyZoo#354]

**Comment by Ezra521** [comment]
一样

**Comment by vran-dev** [comment]
文档内有解决方案

https://github.com/vran-dev/PrettyZoo/blob/master/README_CN.md#mac-%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98
