### ISSUE TITLE
win10 0.32版本运行没报错也没可视化界面

### ISSUE THREAD

**Issue by ly2325yj** [vran-dev/PrettyZoo#37]

**Comment by vran-dev** [comment]
是  msi 安装包吗？

可以参考 https://github.com/vran-dev/PrettyZoo/issues/24#issuecomment-741718937 这里的解决方案

**Comment by vran-dev** [comment]
问题解决了吗？ 没问题就我就关闭该 issue 了

**Comment by ly2325yj** [comment]
结束了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "vran-dev"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 下午2:44
收件人: "vran-dev/PrettyZoo"<PrettyZoo@noreply.github.com&gt;; 
抄送: "Ly2325"<714549847@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vran-dev/PrettyZoo] win10 0.32版本运行没报错也没可视化界面 (#37)





 
问题解决了吗？ 没问题就我就关闭该 issue 了
