### ISSUE TITLE
关于节点内容中文乱码问题

### ISSUE THREAD

**Issue by EdwardLee721** [vran-dev/PrettyZoo#39]
## PrettyZoo 版本
version: v1.0.0
type: msi

## 操作系统版本
windows 10

## 问题描述
节点数据存储时设置编码为utf-8，使用PrettyZoo查看显示中文乱码，希望考虑一下增加切换编码功能

**Comment by vran-dev** [comment]
确有编码问题，我会在后续迭代中进行规划
