### ISSUE TITLE
add to ssh tunnel support

### ISSUE THREAD

**Issue by clevertension** [vran-dev/PrettyZoo#4]
![image](https://user-images.githubusercontent.com/346723/75943583-575ad300-5ed0-11ea-9693-d73403a56ac2.png)

currently it only support to {ip:port} connect, but in the production environment, the zookeeper only open port in the internal network, so it is better to support ssh tunnel

**Comment by vran-dev** [comment]
> ![image](https://user-images.githubusercontent.com/346723/75943583-575ad300-5ed0-11ea-9693-d73403a56ac2.png)
> 
> currently it only support to {ip:port} connect, but in the production environment, the zookeeper only open port in the internal network, so it is better to support ssh tunnel

it's a good suggestion, i will support it for next version
