### ISSUE TITLE
可以增加个控制台输入命令吗

### ISSUE THREAD

**Issue by liuchao1996** [vran-dev/PrettyZoo#41]
可以增加个控制台输入命令吗

**Comment by vran-dev** [comment]
@liuchao1996   

我也有过这样的想法，  这一块有什么现成的方案可以实现命令解析，交互的吗？

**Comment by vran-dev** [comment]
欢迎尝试 v1.2.0-BETA 版， 实现了简单的命令行操作

https://github.com/vran-dev/PrettyZoo/releases/tag/v1.2.0-BETA
