### ISSUE TITLE
win10下的prettylog非常庞大，达到了50GB

### ISSUE THREAD

**Issue by chenxk** [vran-dev/PrettyZoo#42]
今天发现C盘突然暴涨，然后查询大文件，发现 .prettyzoo下的日志文件特别大，其中一个达到了50GB。阔怕~

**Comment by vran-dev** [comment]
这个的确是我考虑不周了，我尽快发一个版本，限制日志的大小

**Comment by chenxk** [comment]
Nice

**Comment by vran-dev** [comment]
https://github.com/vran-dev/PrettyZoo/releases/tag/v1.0.1

预览版已经调整了日志规则，只保留 3 天的日志，单个日志文件限制最大 25 MB
