### ISSUE TITLE
数字的字体太难看

### ISSUE THREAD

**Issue by 474903784** [vran-dev/PrettyZoo#43]
数字的字体太难看，一大一小且歪歪扭扭，很容易看错

**Comment by vran-dev** [comment]
> 数字的字体太难看，一大一小且歪歪扭扭，很容易看错

涉及 UI、字体的调整希望你能提供一下**操作系统信息（类型、版本）**、**屏幕分辨率**以及当前使用的 **prettyZoo 版本号**， 这样有助于我做更细致的改进

**Comment by 474903784** [comment]
![1](https://user-images.githubusercontent.com/19564665/102312706-299bd200-3faa-11eb-9cf2-eefea526c76d.png)
系统：Windows 7 专业版 Service Pack 1
分辨率：1920*1080
prettyZoo：1.0.0

**Comment by vran-dev** [comment]
> ![1](https://user-images.githubusercontent.com/19564665/102312706-299bd200-3faa-11eb-9cf2-eefea526c76d.png)
> 系统：Windows 7 专业版 Service Pack 1
> 分辨率：1920*1080
> prettyZoo：1.0.0

你有改过系统的默认字体吗？
