### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by kaixinbaba** [vran-dev/PrettyZoo#52]
## PrettyZoo 版本
version: v1.1.0
type: dmg

## 操作系统版本
Mac BigSur
11.0.1

## 本地 JDK 版本
8 14

## 问题描述
建议：
- `ctime`和`mtime`可以修改（或新增字段）为格式化日期比如 yyyy-MM-dd HH:mm:ss.SSS 这种比较友好
- 另外在 data 显示的部分，可以增加按钮可以切换字符串格式化的方案，比较常用的是 json 或者 xml 这种在 raw string 之间切换，因为 ZK 上存数据，如果数据比较长一般都是存成 json 字符串，如果能格式化展示会非常友好，类似 postman 提供的
- UI 的话，审美什么我也提供不了建议，但是左边的连接管理页面能不能有个 tab 可以切换显示隐藏（伸缩效果），因为我连上后，手动拖拽隐藏的话，如果之后调整界面大小的话 又会显示出来

其他做的挺好，加油啊～

**Comment by vran-dev** [comment]
非常棒的建议，good job～

**Comment by vran-dev** [comment]
hello, 我刚刚发布了 v1.2.0, 这个版本中加入了

-  【建议】 **mtime / ctime 字段格式切换功能** 
-  【建议】 **xml / json 数据格式化** 
- 命令行操作

你可以在在这儿下载并试用
https://github.com/vran-dev/PrettyZoo/releases/tag/v1.2.0

**Comment by kaixinbaba** [comment]
靠谱！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vran-dev <notifications@github.com&gt;
发送时间: 2020年12月30日 19:48
收件人: vran-dev/PrettyZoo <PrettyZoo@noreply.github.com&gt;
抄送: Jeff Xun <452914639@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[vran-dev/PrettyZoo] 建议 (#52)
