### ISSUE TITLE
ubuntu 18.04 install ok, but run failed.

### ISSUE THREAD

**Issue by zhoulicun** [vran-dev/PrettyZoo#60]

**Comment by vran-dev** [comment]
what version  are you using ?

**Comment by vran-dev** [comment]
hello， I install deb package and run it at Ubuntu 18.04, it's ok.

i release new version v1.2.0 , you can try it 

https://github.com/vran-dev/PrettyZoo/releases/tag/v1.2.0

**Comment by zhoulicun** [comment]
> hello， I install deb package and run it at Ubuntu 18.04, it's ok.
> 
> i release new version v1.2.0 , you can try it
> 
> https://github.com/vran-dev/PrettyZoo/releases/tag/v1.2.0

nice, thank you.
