### ISSUE TITLE
1.3.0 msi版本无法打开应用

### ISSUE THREAD

**Issue by wylnoword** [vran-dev/PrettyZoo#73]
## PrettyZoo 版本
version: v1.3.0
type: msi 

## 操作系统版本
windows 10

## 本地 JDK 版本
java -version:
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

## 问题描述
无法打开应用,双击无响应

## 日志信息
```java
```

**Comment by vran-dev** [comment]
@wylnoword 

前面 release 里面的版本还是1.2.0， 我重新打包了以下，你再下载安装试试呢？

你可以现在这里看一下版本是否是正确的

![image](https://user-images.githubusercontent.com/12870335/104013760-e15c8200-51ec-11eb-94c7-91714820432d.png)

**Comment by wylnoword** [comment]
刚刚下的最新包还是不行。哪里可以看日志？

**Comment by vran-dev** [comment]
> 刚刚下的最新包还是不行。哪里可以看日志？

在 `{用户目录}/.prettyZoo` 目录下有日志

我刚刚试了下，也是 win10 的环境，安装后可以打开，  有试过重启吗？

**Comment by wylnoword** [comment]
![1610110044(1)](https://user-images.githubusercontent.com/43903008/104017489-2be0fd00-51f3-11eb-978d-e908310888f0.png)
![1610110096(1)](https://user-images.githubusercontent.com/43903008/104017501-313e4780-51f3-11eb-86fa-f9485d3142e6.png)
![1610110165(1)](https://user-images.githubusercontent.com/43903008/104017507-34d1ce80-51f3-11eb-86a5-d4bbcd1f499e.png)
重启后也不行，{用户目录}下也没有生成 .prettyZoo目录...

**Comment by vran-dev** [comment]
@wylnoword 

我这边有两个排查方向

一，先将环境变量中的 JAVA_HOME 指向一个不存在的目录，然后启动 prettyZoo，如果能启动，说明 JDK 版本有问题

二，在用户目录下手动创建 .prettyZoo 目录， 并在目录下创建一个 server-input.history 的文件， 文件内容如下
```json
{}
```
然后启动， 如果启动成功，说明应用没有权限在用户目录下创建配置文件的权限

**Comment by wylnoword** [comment]
定位到。安装到默认目录能用，改到d:/目录下不行。（没有中文目录）

**Comment by vran-dev** [comment]
@wylnoword 

难道是因为在 D 盘目录下无法访问 C 盘？或者是有其他特殊场景？

下面这段代码是 PrettyZoo 创建配置的片段，希望你能帮我在你的机器上验证一下：在 D 盘运行是不是会出现异常？

```java
 try {
    String jsonFile = System.getProperty("user.home") + "/.prettyZoo/server-input.history";
    final Path path = Paths.get(jsonFile);
    if (!Files.exists(path)) {
        Files.createFile(path);
        Files.write(path, "{}".getBytes(), StandardOpenOption.WRITE);
    }
  } catch (IOException e) {
      throw new IllegalStateException(e);
  }

```

如果的确是异常情况，我会尝试去一劳永逸的解决掉， 非常感谢

**Comment by wylnoword** [comment]
存在..prettyZoo目录的情况下，d盘运行以上代码不会报错。
手动删除server-input.history文件后，运行代码成功创建server-input.history文件

**Comment by 28723249** [comment]
我的笔记本也是win10，安装最新的1.3.0，重启后，仍然无法运行prettyZoo。
几点说明：
1、我的电脑上运行System.getProperty("user.home")后，得到的用户Home目录中含有中文；
2、用户Home目录没有自动创建出.prettyZoo目录。

**Comment by 28723249** [comment]
> @wylnoword
> 
> 难道是因为在 D 盘目录下无法访问 C 盘？或者是有其他特殊场景？
> 
> 下面这段代码是 PrettyZoo 创建配置的片段，希望你能帮我在你的机器上验证一下：在 D 盘运行是不是会出现异常？
> 
> ```java
>  try {
>     String jsonFile = System.getProperty("user.home") + "/.prettyZoo/server-input.history";
>     final Path path = Paths.get(jsonFile);
>     if (!Files.exists(path)) {
>         Files.createFile(path);
>         Files.write(path, "{}".getBytes(), StandardOpenOption.WRITE);
>     }
>   } catch (IOException e) {
>       throw new IllegalStateException(e);
>   }
> ```
> 
> 如果的确是异常情况，我会尝试去一劳永逸的解决掉， 非常感谢

我的笔记本也是win10，安装最新的1.3.0，重启后，仍然无法运行prettyZoo。
几点说明：
1、我的电脑上运行System.getProperty("user.home")后，得到的用户Home目录中含有中文；
2、用户Home目录没有自动创建出.prettyZoo目录。

**Comment by vran-dev** [comment]
@28723249 @wylnoword 

我刚刚发布了 Pre release  版本 v1.3.1， 尝试去修复了启动不了的情况。

如果有空的话可以帮忙验证以一下，谢谢

**Comment by 28723249** [comment]
[](url)

> @28723249 @wylnoword
> 
> 我刚刚发布了 Pre release 版本 v1.3.1， 尝试去修复了启动不了的情况。
> 
> 如果有空的话可以帮忙验证以一下，谢谢

刚用1.3.1版本试了下，最终结论：可以正常运行。
我的win10用户是中文名称，所以用户Home目录含有中文，安装过程中还是碰到了问题：
1、直接安装在默认目录下（带中文用户名的用户Home目录），无法启动，也没有在用户Home目录下生成.prettyZoo目录；
2、卸载默认位置的安装数据，重新安装到另一个分区不带中文不包含空格的目录（比如：g:\software\PrettyZoo\）下，可以正常启动。

**还有个有个关于字体的问题：**
我有另一台win7的电脑，使用默认安装目录（用户名为英文）可以正常启动，但是字体有大有小，看起来比较奇怪，如下图：

![font](https://user-images.githubusercontent.com/10138589/104153435-50202200-541d-11eb-95ad-351170cf7d0a.png)

**还发现一个bug：**
当服务器列表中（下图中标1的区域）只有一个条目时，如果关闭了标2的那个窗口，则无法再打开该窗口。

![error](https://user-images.githubusercontent.com/10138589/104153848-5e227280-541e-11eb-9298-80bea05cb08a.png)

**Comment by xiaolongyuan** [comment]
win 10  xps9560 4k屏 jdk11  有问题
![image](https://user-images.githubusercontent.com/3142363/104171468-abfaa300-543d-11eb-9fb8-f2106ff3d819.png)

**Comment by vran-dev** [comment]
> > @28723249 @wylnoword
> > 我刚刚发布了 Pre release 版本 v1.3.1， 尝试去修复了启动不了的情况。
> > 如果有空的话可以帮忙验证以一下，谢谢
> 
> 刚用1.3.1版本试了下，最终结论：可以正常运行。
> 我的win10用户是中文名称，所以用户Home目录含有中文，安装过程中还是碰到了问题：
> 1、直接安装在默认目录下（带中文用户名的用户Home目录），无法启动，也没有在用户Home目录下生成.prettyZoo目录；
> 2、卸载默认位置的安装数据，重新安装到另一个分区不带中文不包含空格的目录（比如：g:\software\PrettyZoo\）下，可以正常启动。
> 
> **还有个关于字体的小问题：**
> 我有另一台win7的电脑，使用默认安装目录（用户名为英文）可以正常启动，但是字体有大有小，看起来比较奇怪，如下图：
> 
> ![font](https://user-images.githubusercontent.com/10138589/104153435-50202200-541d-11eb-95ad-351170cf7d0a.png)
> 
> **还发现一个bug：**
> 当服务器列表中（下图中标1的区域）只有一个条目时，如果关闭了标2的那个窗口，则无法再打开该窗口。
> 
> ![error](https://user-images.githubusercontent.com/10138589/104153848-5e227280-541e-11eb-9298-80bea05cb08a.png)

Thanks,  我会在后续的迭代中修复对应的 BUG

**Comment by vran-dev** [comment]
> win 10 xps9560 4k屏 jdk11 有问题
> ![image](https://user-images.githubusercontent.com/3142363/104171468-abfaa300-543d-11eb-9fb8-f2106ff3d819.png)

能描述一下具体的问题吗？

**Comment by vran-dev** [comment]
@28723249 

关于那个 bug 的问题，你能单独提一个 ISSUE 吗？感谢

**Comment by vran-dev** [comment]
@xiaolongyuan  你那边的问题也可以单独提一个 issue 描述一下详细的问题

**Comment by 28723249** [comment]
> @28723249
> 
> 关于那个 bug 的问题，你能单独提一个 ISSUE 吗？感谢

已提。
