### ISSUE TITLE
当服务器列表中只有一个条目时，如果关闭了展示区的那个窗口，则无法再打开该窗口。

### ISSUE THREAD

**Issue by 28723249** [vran-dev/PrettyZoo#78]
当服务器列表中（下图中标1的区域）只有一个条目时，如果关闭了标2的那个窗口，则无法再打开该窗口。如下图：

![bug](https://user-images.githubusercontent.com/10138589/104258790-2a495a80-54bb-11eb-9d27-5b36149a410a.png)

**Comment by vran-dev** [comment]
thanks

**Comment by 28723249** [comment]
> thanks

客气哈
