### ISSUE TITLE
双击应用无法打开

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [vran-dev/PrettyZoo#87]
## PrettyZoo 版本
version: v1.3.1
type: msi / exe

## 操作系统版本
windows 10

## 本地 JDK 版本
有，jdk8

## 问题描述
安装完成后双击无法打开

## 日志信息
没有发现日志在哪里

**Comment by vran-dev** [comment]
@wojiaoxiaomayun 

检查用户目录下是否存在 `{user.home}/.prettyZoo` 目录

可以尝试在不修改默认安装路径情况下，重新进行安装试试？

**Comment by wojiaoxiaomayun** [comment]
![image](https://user-images.githubusercontent.com/30283623/105619686-147b5400-5e30-11eb-9e28-3689a6660fa7.png)
尝试了不修改默认安装路径

**Comment by vran-dev** [comment]
@wojiaoxiaomayun 

似乎和中文路径有关， 你可以手动在用户目录下创建 `.prettyZoo` 文件夹，再在 `.prettyZoo` 下创建一个名为 `.server-input.history` 的文件， 文件内容如下

```json
{}
```

这样应该就可以启动了，我会在后续版本中尝试修复该问题

**Comment by wojiaoxiaomayun** [comment]
创建了，还是不太好使，我期待后续版本吧，谢谢大佬
