### ISSUE TITLE
中文乱码问题和连接别名问题

### ISSUE THREAD

**Issue by ywxys** [vran-dev/PrettyZoo#98]
中文乱码问题建议在prettyZoo.cfg文件中增加
[JavaOptions]
-Djdk.gtk.version=2
-Dfile.encoding=utf-8
连接别名问题，配置多个连接时，现在通过ip和端口的方式展示，没办法通过别名快速找到对应环境

**Comment by vran-dev** [comment]
中文乱码指的是 node 吗？

关于多个连接查找不便的问题我会在后面优化一下

感谢你的建议

**Comment by ywxys** [comment]
乱码是指node的value
